// Code generated by protoc-gen-gogo.
// source: internal/meta.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal/meta.proto

It has these top-level messages:
	ClusterData
	NodeInfo
	RoleInfo
	UserInfo
	UserPrivilege
	ScopedPermission
	Response
	Command
	CreateDatabaseCommand
	DropDatabaseCommand
	CreateRetentionPolicyCommand
	DropRetentionPolicyCommand
	SetDefaultRetentionPolicyCommand
	UpdateRetentionPolicyCommand
	CreateShardGroupCommand
	DeleteShardGroupCommand
	CreateContinuousQueryCommand
	DropContinuousQueryCommand
	CreateUserCommand
	DropUserCommand
	UpdateUserCommand
	SetPrivilegeCommand
	CreateRoleCommand
	DropRoleCommand
	AddRoleUsersCommand
	RemoveRoleUsersCommand
	AddRolePermissionsCommand
	RemoveRolePermissionsCommand
	SetDataCommand
	SetAdminPrivilegeCommand
	CreateSubscriptionCommand
	DropSubscriptionCommand
	RemovePeerCommand
	CreateMetaNodeCommand
	CreateDataNodeCommand
	UpdateDataNodeCommand
	DeleteMetaNodeCommand
	DeleteDataNodeCommand
	SetMetaNodeCommand
	DropShardCommand
	SetUserPasswordCommand
	AddUserPermissionsCommand
	RemoveUserPermissionsCommand
	AddShardOwnerCommand
	RemoveShardOwnerCommand
	AddPendingShardOwnerCommand
	RemovePendingShardOwnerCommand
	CommitPendingShardOwnerCommand
	TruncateShardGroupCommand
	ChangeRoleNameCommand
	ImportDataCommand
	CreateBalancedShardGroupCommand
*/
package internal

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Command_Type int32

const (
	Command_CreateDatabaseCommand            Command_Type = 1
	Command_DropDatabaseCommand              Command_Type = 2
	Command_CreateRetentionPolicyCommand     Command_Type = 3
	Command_DropRetentionPolicyCommand       Command_Type = 4
	Command_SetDefaultRetentionPolicyCommand Command_Type = 5
	Command_UpdateRetentionPolicyCommand     Command_Type = 6
	Command_CreateShardGroupCommand          Command_Type = 7
	Command_DeleteShardGroupCommand          Command_Type = 8
	Command_CreateContinuousQueryCommand     Command_Type = 9
	Command_DropContinuousQueryCommand       Command_Type = 10
	Command_CreateUserCommand                Command_Type = 11
	Command_DropUserCommand                  Command_Type = 12
	Command_UpdateUserCommand                Command_Type = 13
	Command_SetPrivilegeCommand              Command_Type = 14
	Command_CreateRoleCommand                Command_Type = 15
	Command_DropRoleCommand                  Command_Type = 16
	Command_AddRoleUsersCommand              Command_Type = 17
	Command_RemoveRoleUsersCommand           Command_Type = 18
	Command_AddRolePermissionsCommand        Command_Type = 19
	Command_RemoveRolePermissionsCommand     Command_Type = 20
	Command_SetDataCommand                   Command_Type = 21
	Command_SetAdminPrivilegeCommand         Command_Type = 22
	Command_CreateSubscriptionCommand        Command_Type = 23
	Command_DropSubscriptionCommand          Command_Type = 24
	Command_RemovePeerCommand                Command_Type = 25
	Command_CreateMetaNodeCommand            Command_Type = 26
	Command_CreateDataNodeCommand            Command_Type = 27
	Command_UpdateDataNodeCommand            Command_Type = 28
	Command_DeleteMetaNodeCommand            Command_Type = 29
	Command_DeleteDataNodeCommand            Command_Type = 30
	Command_SetMetaNodeCommand               Command_Type = 31
	Command_DropShardCommand                 Command_Type = 32
	Command_ImportDataCommand                Command_Type = 33
	Command_SetUserPasswordCommand           Command_Type = 34
	Command_AddUserPermissionsCommand        Command_Type = 35
	Command_RemoveUserPermissionsCommand     Command_Type = 36
	Command_AddShardOwnerCommand             Command_Type = 37
	Command_RemoveShardOwnerCommand          Command_Type = 38
	Command_AddPendingShardOwnerCommand      Command_Type = 39
	Command_CommitPendingShardOwnerCommand   Command_Type = 40
	Command_RemovePendingShardOwnerCommand   Command_Type = 41
	Command_TruncateShardGroupsCommand       Command_Type = 42
	Command_ChangeRoleNameCommand            Command_Type = 43
	Command_CreateBalancedShardGroupCommand  Command_Type = 44
)

var Command_Type_name = map[int32]string{
	1:  "CreateDatabaseCommand",
	2:  "DropDatabaseCommand",
	3:  "CreateRetentionPolicyCommand",
	4:  "DropRetentionPolicyCommand",
	5:  "SetDefaultRetentionPolicyCommand",
	6:  "UpdateRetentionPolicyCommand",
	7:  "CreateShardGroupCommand",
	8:  "DeleteShardGroupCommand",
	9:  "CreateContinuousQueryCommand",
	10: "DropContinuousQueryCommand",
	11: "CreateUserCommand",
	12: "DropUserCommand",
	13: "UpdateUserCommand",
	14: "SetPrivilegeCommand",
	15: "CreateRoleCommand",
	16: "DropRoleCommand",
	17: "AddRoleUsersCommand",
	18: "RemoveRoleUsersCommand",
	19: "AddRolePermissionsCommand",
	20: "RemoveRolePermissionsCommand",
	21: "SetDataCommand",
	22: "SetAdminPrivilegeCommand",
	23: "CreateSubscriptionCommand",
	24: "DropSubscriptionCommand",
	25: "RemovePeerCommand",
	26: "CreateMetaNodeCommand",
	27: "CreateDataNodeCommand",
	28: "UpdateDataNodeCommand",
	29: "DeleteMetaNodeCommand",
	30: "DeleteDataNodeCommand",
	31: "SetMetaNodeCommand",
	32: "DropShardCommand",
	33: "ImportDataCommand",
	34: "SetUserPasswordCommand",
	35: "AddUserPermissionsCommand",
	36: "RemoveUserPermissionsCommand",
	37: "AddShardOwnerCommand",
	38: "RemoveShardOwnerCommand",
	39: "AddPendingShardOwnerCommand",
	40: "CommitPendingShardOwnerCommand",
	41: "RemovePendingShardOwnerCommand",
	42: "TruncateShardGroupsCommand",
	43: "ChangeRoleNameCommand",
	44: "CreateBalancedShardGroupCommand",
}
var Command_Type_value = map[string]int32{
	"CreateDatabaseCommand":            1,
	"DropDatabaseCommand":              2,
	"CreateRetentionPolicyCommand":     3,
	"DropRetentionPolicyCommand":       4,
	"SetDefaultRetentionPolicyCommand": 5,
	"UpdateRetentionPolicyCommand":     6,
	"CreateShardGroupCommand":          7,
	"DeleteShardGroupCommand":          8,
	"CreateContinuousQueryCommand":     9,
	"DropContinuousQueryCommand":       10,
	"CreateUserCommand":                11,
	"DropUserCommand":                  12,
	"UpdateUserCommand":                13,
	"SetPrivilegeCommand":              14,
	"CreateRoleCommand":                15,
	"DropRoleCommand":                  16,
	"AddRoleUsersCommand":              17,
	"RemoveRoleUsersCommand":           18,
	"AddRolePermissionsCommand":        19,
	"RemoveRolePermissionsCommand":     20,
	"SetDataCommand":                   21,
	"SetAdminPrivilegeCommand":         22,
	"CreateSubscriptionCommand":        23,
	"DropSubscriptionCommand":          24,
	"RemovePeerCommand":                25,
	"CreateMetaNodeCommand":            26,
	"CreateDataNodeCommand":            27,
	"UpdateDataNodeCommand":            28,
	"DeleteMetaNodeCommand":            29,
	"DeleteDataNodeCommand":            30,
	"SetMetaNodeCommand":               31,
	"DropShardCommand":                 32,
	"ImportDataCommand":                33,
	"SetUserPasswordCommand":           34,
	"AddUserPermissionsCommand":        35,
	"RemoveUserPermissionsCommand":     36,
	"AddShardOwnerCommand":             37,
	"RemoveShardOwnerCommand":          38,
	"AddPendingShardOwnerCommand":      39,
	"CommitPendingShardOwnerCommand":   40,
	"RemovePendingShardOwnerCommand":   41,
	"TruncateShardGroupsCommand":       42,
	"ChangeRoleNameCommand":            43,
	"CreateBalancedShardGroupCommand":  44,
}

func (x Command_Type) Enum() *Command_Type {
	p := new(Command_Type)
	*p = x
	return p
}
func (x Command_Type) String() string {
	return proto.EnumName(Command_Type_name, int32(x))
}
func (x *Command_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Command_Type_value, data, "Command_Type")
	if err != nil {
		return err
	}
	*x = Command_Type(value)
	return nil
}
func (Command_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptorMeta, []int{7, 0} }

type ClusterData struct {
	Data             []byte      `protobuf:"bytes,1,req,name=Data" json:"Data,omitempty"`
	MaxNodeID        *uint64     `protobuf:"varint,2,req,name=MaxNodeID" json:"MaxNodeID,omitempty"`
	DataNodes        []*NodeInfo `protobuf:"bytes,3,rep,name=DataNodes" json:"DataNodes,omitempty"`
	MetaNodes        []*NodeInfo `protobuf:"bytes,4,rep,name=MetaNodes" json:"MetaNodes,omitempty"`
	Roles            []*RoleInfo `protobuf:"bytes,5,rep,name=Roles" json:"Roles,omitempty"`
	Users            []*UserInfo `protobuf:"bytes,6,rep,name=Users" json:"Users,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ClusterData) Reset()                    { *m = ClusterData{} }
func (m *ClusterData) String() string            { return proto.CompactTextString(m) }
func (*ClusterData) ProtoMessage()               {}
func (*ClusterData) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{0} }

func (m *ClusterData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ClusterData) GetMaxNodeID() uint64 {
	if m != nil && m.MaxNodeID != nil {
		return *m.MaxNodeID
	}
	return 0
}

func (m *ClusterData) GetDataNodes() []*NodeInfo {
	if m != nil {
		return m.DataNodes
	}
	return nil
}

func (m *ClusterData) GetMetaNodes() []*NodeInfo {
	if m != nil {
		return m.MetaNodes
	}
	return nil
}

func (m *ClusterData) GetRoles() []*RoleInfo {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *ClusterData) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type NodeInfo struct {
	ID                 *uint64  `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Host               *string  `protobuf:"bytes,2,req,name=Host" json:"Host,omitempty"`
	TCPHost            *string  `protobuf:"bytes,3,opt,name=TCPHost" json:"TCPHost,omitempty"`
	PendingShardOwners []uint64 `protobuf:"varint,4,rep,name=PendingShardOwners" json:"PendingShardOwners,omitempty"`
	XXX_unrecognized   []byte   `json:"-"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{1} }

func (m *NodeInfo) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *NodeInfo) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *NodeInfo) GetTCPHost() string {
	if m != nil && m.TCPHost != nil {
		return *m.TCPHost
	}
	return ""
}

func (m *NodeInfo) GetPendingShardOwners() []uint64 {
	if m != nil {
		return m.PendingShardOwners
	}
	return nil
}

type RoleInfo struct {
	Name             *string        `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Permissions      *UserPrivilege `protobuf:"bytes,2,req,name=Permissions" json:"Permissions,omitempty"`
	Users            *UserInfo      `protobuf:"bytes,3,req,name=Users" json:"Users,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RoleInfo) Reset()                    { *m = RoleInfo{} }
func (m *RoleInfo) String() string            { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()               {}
func (*RoleInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{2} }

func (m *RoleInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RoleInfo) GetPermissions() *UserPrivilege {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *RoleInfo) GetUsers() *UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserInfo struct {
	Name             *string          `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Hash             *string          `protobuf:"bytes,2,req,name=Hash" json:"Hash,omitempty"`
	Permissions      []*UserPrivilege `protobuf:"bytes,3,rep,name=Permissions" json:"Permissions,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{3} }

func (m *UserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserInfo) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *UserInfo) GetPermissions() []*UserPrivilege {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type UserPrivilege struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Privilege        *int32  `protobuf:"varint,2,req,name=Privilege" json:"Privilege,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserPrivilege) Reset()                    { *m = UserPrivilege{} }
func (m *UserPrivilege) String() string            { return proto.CompactTextString(m) }
func (*UserPrivilege) ProtoMessage()               {}
func (*UserPrivilege) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{4} }

func (m *UserPrivilege) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *UserPrivilege) GetPrivilege() int32 {
	if m != nil && m.Privilege != nil {
		return *m.Privilege
	}
	return 0
}

type ScopedPermission struct {
	Resources        []byte         `protobuf:"bytes,1,req,name=Resources" json:"Resources,omitempty"`
	Permissions      *UserPrivilege `protobuf:"bytes,2,req,name=Permissions" json:"Permissions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ScopedPermission) Reset()                    { *m = ScopedPermission{} }
func (m *ScopedPermission) String() string            { return proto.CompactTextString(m) }
func (*ScopedPermission) ProtoMessage()               {}
func (*ScopedPermission) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{5} }

func (m *ScopedPermission) GetResources() []byte {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *ScopedPermission) GetPermissions() *UserPrivilege {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type Response struct {
	OK               *bool   `protobuf:"varint,1,req,name=OK" json:"OK,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=Error" json:"Error,omitempty"`
	Index            *uint64 `protobuf:"varint,3,opt,name=Index" json:"Index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{6} }

func (m *Response) GetOK() bool {
	if m != nil && m.OK != nil {
		return *m.OK
	}
	return false
}

func (m *Response) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *Response) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type Command struct {
	Type                         *Command_Type `protobuf:"varint,1,req,name=type,enum=internal.Command_Type" json:"type,omitempty"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{7} }

var extRange_Command = []proto.ExtensionRange{
	{Start: 100, End: 536870911},
}

func (*Command) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Command
}

func (m *Command) GetType() Command_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Command_CreateDatabaseCommand
}

type CreateDatabaseCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	RetentionPolicy  []byte  `protobuf:"bytes,2,opt,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateDatabaseCommand) Reset()                    { *m = CreateDatabaseCommand{} }
func (m *CreateDatabaseCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateDatabaseCommand) ProtoMessage()               {}
func (*CreateDatabaseCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{8} }

func (m *CreateDatabaseCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateDatabaseCommand) GetRetentionPolicy() []byte {
	if m != nil {
		return m.RetentionPolicy
	}
	return nil
}

var E_CreateDatabaseCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateDatabaseCommand)(nil),
	Field:         101,
	Name:          "internal.CreateDatabaseCommand.command",
	Tag:           "bytes,101,opt,name=command",
}

type DropDatabaseCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropDatabaseCommand) Reset()                    { *m = DropDatabaseCommand{} }
func (m *DropDatabaseCommand) String() string            { return proto.CompactTextString(m) }
func (*DropDatabaseCommand) ProtoMessage()               {}
func (*DropDatabaseCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{9} }

func (m *DropDatabaseCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_DropDatabaseCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropDatabaseCommand)(nil),
	Field:         102,
	Name:          "internal.DropDatabaseCommand.command",
	Tag:           "bytes,102,opt,name=command",
}

type CreateRetentionPolicyCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	RetentionPolicy  []byte  `protobuf:"bytes,2,req,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRetentionPolicyCommand) Reset()         { *m = CreateRetentionPolicyCommand{} }
func (m *CreateRetentionPolicyCommand) String() string { return proto.CompactTextString(m) }
func (*CreateRetentionPolicyCommand) ProtoMessage()    {}
func (*CreateRetentionPolicyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{10}
}

func (m *CreateRetentionPolicyCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CreateRetentionPolicyCommand) GetRetentionPolicy() []byte {
	if m != nil {
		return m.RetentionPolicy
	}
	return nil
}

var E_CreateRetentionPolicyCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateRetentionPolicyCommand)(nil),
	Field:         103,
	Name:          "internal.CreateRetentionPolicyCommand.command",
	Tag:           "bytes,103,opt,name=command",
}

type DropRetentionPolicyCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropRetentionPolicyCommand) Reset()                    { *m = DropRetentionPolicyCommand{} }
func (m *DropRetentionPolicyCommand) String() string            { return proto.CompactTextString(m) }
func (*DropRetentionPolicyCommand) ProtoMessage()               {}
func (*DropRetentionPolicyCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{11} }

func (m *DropRetentionPolicyCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *DropRetentionPolicyCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_DropRetentionPolicyCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropRetentionPolicyCommand)(nil),
	Field:         104,
	Name:          "internal.DropRetentionPolicyCommand.command",
	Tag:           "bytes,104,opt,name=command",
}

type SetDefaultRetentionPolicyCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetDefaultRetentionPolicyCommand) Reset()         { *m = SetDefaultRetentionPolicyCommand{} }
func (m *SetDefaultRetentionPolicyCommand) String() string { return proto.CompactTextString(m) }
func (*SetDefaultRetentionPolicyCommand) ProtoMessage()    {}
func (*SetDefaultRetentionPolicyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{12}
}

func (m *SetDefaultRetentionPolicyCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *SetDefaultRetentionPolicyCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_SetDefaultRetentionPolicyCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetDefaultRetentionPolicyCommand)(nil),
	Field:         105,
	Name:          "internal.SetDefaultRetentionPolicyCommand.command",
	Tag:           "bytes,105,opt,name=command",
}

type UpdateRetentionPolicyCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	NewName          *string `protobuf:"bytes,3,opt,name=NewName" json:"NewName,omitempty"`
	Duration         *int64  `protobuf:"varint,4,opt,name=Duration" json:"Duration,omitempty"`
	ReplicaN         *uint32 `protobuf:"varint,5,opt,name=ReplicaN" json:"ReplicaN,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateRetentionPolicyCommand) Reset()         { *m = UpdateRetentionPolicyCommand{} }
func (m *UpdateRetentionPolicyCommand) String() string { return proto.CompactTextString(m) }
func (*UpdateRetentionPolicyCommand) ProtoMessage()    {}
func (*UpdateRetentionPolicyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{13}
}

func (m *UpdateRetentionPolicyCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *UpdateRetentionPolicyCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UpdateRetentionPolicyCommand) GetNewName() string {
	if m != nil && m.NewName != nil {
		return *m.NewName
	}
	return ""
}

func (m *UpdateRetentionPolicyCommand) GetDuration() int64 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *UpdateRetentionPolicyCommand) GetReplicaN() uint32 {
	if m != nil && m.ReplicaN != nil {
		return *m.ReplicaN
	}
	return 0
}

var E_UpdateRetentionPolicyCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*UpdateRetentionPolicyCommand)(nil),
	Field:         106,
	Name:          "internal.UpdateRetentionPolicyCommand.command",
	Tag:           "bytes,106,opt,name=command",
}

type CreateShardGroupCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Policy           *string `protobuf:"bytes,2,req,name=Policy" json:"Policy,omitempty"`
	Timestamp        *int64  `protobuf:"varint,3,req,name=Timestamp" json:"Timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateShardGroupCommand) Reset()                    { *m = CreateShardGroupCommand{} }
func (m *CreateShardGroupCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateShardGroupCommand) ProtoMessage()               {}
func (*CreateShardGroupCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{14} }

func (m *CreateShardGroupCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CreateShardGroupCommand) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *CreateShardGroupCommand) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

var E_CreateShardGroupCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateShardGroupCommand)(nil),
	Field:         107,
	Name:          "internal.CreateShardGroupCommand.command",
	Tag:           "bytes,107,opt,name=command",
}

type DeleteShardGroupCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Policy           *string `protobuf:"bytes,2,req,name=Policy" json:"Policy,omitempty"`
	ShardGroupID     *uint64 `protobuf:"varint,3,req,name=ShardGroupID" json:"ShardGroupID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteShardGroupCommand) Reset()                    { *m = DeleteShardGroupCommand{} }
func (m *DeleteShardGroupCommand) String() string            { return proto.CompactTextString(m) }
func (*DeleteShardGroupCommand) ProtoMessage()               {}
func (*DeleteShardGroupCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{15} }

func (m *DeleteShardGroupCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *DeleteShardGroupCommand) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *DeleteShardGroupCommand) GetShardGroupID() uint64 {
	if m != nil && m.ShardGroupID != nil {
		return *m.ShardGroupID
	}
	return 0
}

var E_DeleteShardGroupCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DeleteShardGroupCommand)(nil),
	Field:         108,
	Name:          "internal.DeleteShardGroupCommand.command",
	Tag:           "bytes,108,opt,name=command",
}

type CreateContinuousQueryCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	Query            *string `protobuf:"bytes,3,req,name=Query" json:"Query,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateContinuousQueryCommand) Reset()         { *m = CreateContinuousQueryCommand{} }
func (m *CreateContinuousQueryCommand) String() string { return proto.CompactTextString(m) }
func (*CreateContinuousQueryCommand) ProtoMessage()    {}
func (*CreateContinuousQueryCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{16}
}

func (m *CreateContinuousQueryCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CreateContinuousQueryCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateContinuousQueryCommand) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

var E_CreateContinuousQueryCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateContinuousQueryCommand)(nil),
	Field:         109,
	Name:          "internal.CreateContinuousQueryCommand.command",
	Tag:           "bytes,109,opt,name=command",
}

type DropContinuousQueryCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropContinuousQueryCommand) Reset()                    { *m = DropContinuousQueryCommand{} }
func (m *DropContinuousQueryCommand) String() string            { return proto.CompactTextString(m) }
func (*DropContinuousQueryCommand) ProtoMessage()               {}
func (*DropContinuousQueryCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{17} }

func (m *DropContinuousQueryCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *DropContinuousQueryCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_DropContinuousQueryCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropContinuousQueryCommand)(nil),
	Field:         110,
	Name:          "internal.DropContinuousQueryCommand.command",
	Tag:           "bytes,110,opt,name=command",
}

type CreateUserCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Hash             *string `protobuf:"bytes,2,req,name=Hash" json:"Hash,omitempty"`
	Admin            *bool   `protobuf:"varint,3,req,name=Admin" json:"Admin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateUserCommand) Reset()                    { *m = CreateUserCommand{} }
func (m *CreateUserCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateUserCommand) ProtoMessage()               {}
func (*CreateUserCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{18} }

func (m *CreateUserCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateUserCommand) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *CreateUserCommand) GetAdmin() bool {
	if m != nil && m.Admin != nil {
		return *m.Admin
	}
	return false
}

var E_CreateUserCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateUserCommand)(nil),
	Field:         111,
	Name:          "internal.CreateUserCommand.command",
	Tag:           "bytes,111,opt,name=command",
}

type DropUserCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropUserCommand) Reset()                    { *m = DropUserCommand{} }
func (m *DropUserCommand) String() string            { return proto.CompactTextString(m) }
func (*DropUserCommand) ProtoMessage()               {}
func (*DropUserCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{19} }

func (m *DropUserCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_DropUserCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropUserCommand)(nil),
	Field:         112,
	Name:          "internal.DropUserCommand.command",
	Tag:           "bytes,112,opt,name=command",
}

type UpdateUserCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Hash             *string `protobuf:"bytes,2,req,name=Hash" json:"Hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateUserCommand) Reset()                    { *m = UpdateUserCommand{} }
func (m *UpdateUserCommand) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserCommand) ProtoMessage()               {}
func (*UpdateUserCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{20} }

func (m *UpdateUserCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UpdateUserCommand) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

var E_UpdateUserCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*UpdateUserCommand)(nil),
	Field:         113,
	Name:          "internal.UpdateUserCommand.command",
	Tag:           "bytes,113,opt,name=command",
}

type SetPrivilegeCommand struct {
	Username         *string `protobuf:"bytes,1,req,name=Username" json:"Username,omitempty"`
	Database         *string `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	Privilege        *int32  `protobuf:"varint,3,req,name=Privilege" json:"Privilege,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetPrivilegeCommand) Reset()                    { *m = SetPrivilegeCommand{} }
func (m *SetPrivilegeCommand) String() string            { return proto.CompactTextString(m) }
func (*SetPrivilegeCommand) ProtoMessage()               {}
func (*SetPrivilegeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{21} }

func (m *SetPrivilegeCommand) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *SetPrivilegeCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *SetPrivilegeCommand) GetPrivilege() int32 {
	if m != nil && m.Privilege != nil {
		return *m.Privilege
	}
	return 0
}

var E_SetPrivilegeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetPrivilegeCommand)(nil),
	Field:         114,
	Name:          "internal.SetPrivilegeCommand.command",
	Tag:           "bytes,114,opt,name=command",
}

type CreateRoleCommand struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateRoleCommand) Reset()                    { *m = CreateRoleCommand{} }
func (m *CreateRoleCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateRoleCommand) ProtoMessage()               {}
func (*CreateRoleCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{22} }

var E_CreateRoleCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateRoleCommand)(nil),
	Field:         115,
	Name:          "internal.CreateRoleCommand.command",
	Tag:           "bytes,115,opt,name=command",
}

type DropRoleCommand struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DropRoleCommand) Reset()                    { *m = DropRoleCommand{} }
func (m *DropRoleCommand) String() string            { return proto.CompactTextString(m) }
func (*DropRoleCommand) ProtoMessage()               {}
func (*DropRoleCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{23} }

var E_DropRoleCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropRoleCommand)(nil),
	Field:         116,
	Name:          "internal.DropRoleCommand.command",
	Tag:           "bytes,116,opt,name=command",
}

type AddRoleUsersCommand struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AddRoleUsersCommand) Reset()                    { *m = AddRoleUsersCommand{} }
func (m *AddRoleUsersCommand) String() string            { return proto.CompactTextString(m) }
func (*AddRoleUsersCommand) ProtoMessage()               {}
func (*AddRoleUsersCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{24} }

var E_AddRoleUsersCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*AddRoleUsersCommand)(nil),
	Field:         117,
	Name:          "internal.AddRoleUsersCommand.command",
	Tag:           "bytes,117,opt,name=command",
}

type RemoveRoleUsersCommand struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RemoveRoleUsersCommand) Reset()                    { *m = RemoveRoleUsersCommand{} }
func (m *RemoveRoleUsersCommand) String() string            { return proto.CompactTextString(m) }
func (*RemoveRoleUsersCommand) ProtoMessage()               {}
func (*RemoveRoleUsersCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{25} }

var E_RemoveRoleUsersCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*RemoveRoleUsersCommand)(nil),
	Field:         118,
	Name:          "internal.RemoveRoleUsersCommand.command",
	Tag:           "bytes,118,opt,name=command",
}

type AddRolePermissionsCommand struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AddRolePermissionsCommand) Reset()                    { *m = AddRolePermissionsCommand{} }
func (m *AddRolePermissionsCommand) String() string            { return proto.CompactTextString(m) }
func (*AddRolePermissionsCommand) ProtoMessage()               {}
func (*AddRolePermissionsCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{26} }

var E_AddRolePermissionsCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*AddRolePermissionsCommand)(nil),
	Field:         119,
	Name:          "internal.AddRolePermissionsCommand.command",
	Tag:           "bytes,119,opt,name=command",
}

type RemoveRolePermissionsCommand struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RemoveRolePermissionsCommand) Reset()         { *m = RemoveRolePermissionsCommand{} }
func (m *RemoveRolePermissionsCommand) String() string { return proto.CompactTextString(m) }
func (*RemoveRolePermissionsCommand) ProtoMessage()    {}
func (*RemoveRolePermissionsCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{27}
}

var E_RemoveRolePermissionsCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*RemoveRolePermissionsCommand)(nil),
	Field:         120,
	Name:          "internal.RemoveRolePermissionsCommand.command",
	Tag:           "bytes,120,opt,name=command",
}

type SetDataCommand struct {
	Data             []byte `protobuf:"bytes,1,req,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetDataCommand) Reset()                    { *m = SetDataCommand{} }
func (m *SetDataCommand) String() string            { return proto.CompactTextString(m) }
func (*SetDataCommand) ProtoMessage()               {}
func (*SetDataCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{28} }

func (m *SetDataCommand) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

var E_SetDataCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetDataCommand)(nil),
	Field:         121,
	Name:          "internal.SetDataCommand.command",
	Tag:           "bytes,121,opt,name=command",
}

type SetAdminPrivilegeCommand struct {
	Username         *string `protobuf:"bytes,1,req,name=Username" json:"Username,omitempty"`
	Admin            *bool   `protobuf:"varint,2,req,name=Admin" json:"Admin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetAdminPrivilegeCommand) Reset()                    { *m = SetAdminPrivilegeCommand{} }
func (m *SetAdminPrivilegeCommand) String() string            { return proto.CompactTextString(m) }
func (*SetAdminPrivilegeCommand) ProtoMessage()               {}
func (*SetAdminPrivilegeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{29} }

func (m *SetAdminPrivilegeCommand) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *SetAdminPrivilegeCommand) GetAdmin() bool {
	if m != nil && m.Admin != nil {
		return *m.Admin
	}
	return false
}

var E_SetAdminPrivilegeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetAdminPrivilegeCommand)(nil),
	Field:         122,
	Name:          "internal.SetAdminPrivilegeCommand.command",
	Tag:           "bytes,122,opt,name=command",
}

type CreateSubscriptionCommand struct {
	Name             *string  `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Database         *string  `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	RetentionPolicy  *string  `protobuf:"bytes,3,req,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	Mode             *string  `protobuf:"bytes,4,req,name=Mode" json:"Mode,omitempty"`
	Destinations     []string `protobuf:"bytes,5,rep,name=Destinations" json:"Destinations,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CreateSubscriptionCommand) Reset()                    { *m = CreateSubscriptionCommand{} }
func (m *CreateSubscriptionCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateSubscriptionCommand) ProtoMessage()               {}
func (*CreateSubscriptionCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{30} }

func (m *CreateSubscriptionCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateSubscriptionCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CreateSubscriptionCommand) GetRetentionPolicy() string {
	if m != nil && m.RetentionPolicy != nil {
		return *m.RetentionPolicy
	}
	return ""
}

func (m *CreateSubscriptionCommand) GetMode() string {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return ""
}

func (m *CreateSubscriptionCommand) GetDestinations() []string {
	if m != nil {
		return m.Destinations
	}
	return nil
}

var E_CreateSubscriptionCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateSubscriptionCommand)(nil),
	Field:         123,
	Name:          "internal.CreateSubscriptionCommand.command",
	Tag:           "bytes,123,opt,name=command",
}

type DropSubscriptionCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Database         *string `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	RetentionPolicy  *string `protobuf:"bytes,3,req,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropSubscriptionCommand) Reset()                    { *m = DropSubscriptionCommand{} }
func (m *DropSubscriptionCommand) String() string            { return proto.CompactTextString(m) }
func (*DropSubscriptionCommand) ProtoMessage()               {}
func (*DropSubscriptionCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{31} }

func (m *DropSubscriptionCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *DropSubscriptionCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *DropSubscriptionCommand) GetRetentionPolicy() string {
	if m != nil && m.RetentionPolicy != nil {
		return *m.RetentionPolicy
	}
	return ""
}

var E_DropSubscriptionCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropSubscriptionCommand)(nil),
	Field:         124,
	Name:          "internal.DropSubscriptionCommand.command",
	Tag:           "bytes,124,opt,name=command",
}

type RemovePeerCommand struct {
	ID               *uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Addr             *string `protobuf:"bytes,2,req,name=Addr" json:"Addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemovePeerCommand) Reset()                    { *m = RemovePeerCommand{} }
func (m *RemovePeerCommand) String() string            { return proto.CompactTextString(m) }
func (*RemovePeerCommand) ProtoMessage()               {}
func (*RemovePeerCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{32} }

func (m *RemovePeerCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *RemovePeerCommand) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

var E_RemovePeerCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*RemovePeerCommand)(nil),
	Field:         125,
	Name:          "internal.RemovePeerCommand.command",
	Tag:           "bytes,125,opt,name=command",
}

type CreateMetaNodeCommand struct {
	HTTPAddr         *string `protobuf:"bytes,1,req,name=HTTPAddr" json:"HTTPAddr,omitempty"`
	TCPAddr          *string `protobuf:"bytes,2,req,name=TCPAddr" json:"TCPAddr,omitempty"`
	Rand             *uint64 `protobuf:"varint,3,req,name=Rand" json:"Rand,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateMetaNodeCommand) Reset()                    { *m = CreateMetaNodeCommand{} }
func (m *CreateMetaNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateMetaNodeCommand) ProtoMessage()               {}
func (*CreateMetaNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{33} }

func (m *CreateMetaNodeCommand) GetHTTPAddr() string {
	if m != nil && m.HTTPAddr != nil {
		return *m.HTTPAddr
	}
	return ""
}

func (m *CreateMetaNodeCommand) GetTCPAddr() string {
	if m != nil && m.TCPAddr != nil {
		return *m.TCPAddr
	}
	return ""
}

func (m *CreateMetaNodeCommand) GetRand() uint64 {
	if m != nil && m.Rand != nil {
		return *m.Rand
	}
	return 0
}

var E_CreateMetaNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateMetaNodeCommand)(nil),
	Field:         126,
	Name:          "internal.CreateMetaNodeCommand.command",
	Tag:           "bytes,126,opt,name=command",
}

type CreateDataNodeCommand struct {
	HTTPAddr         *string `protobuf:"bytes,1,req,name=HTTPAddr" json:"HTTPAddr,omitempty"`
	TCPAddr          *string `protobuf:"bytes,2,req,name=TCPAddr" json:"TCPAddr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateDataNodeCommand) Reset()                    { *m = CreateDataNodeCommand{} }
func (m *CreateDataNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateDataNodeCommand) ProtoMessage()               {}
func (*CreateDataNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{34} }

func (m *CreateDataNodeCommand) GetHTTPAddr() string {
	if m != nil && m.HTTPAddr != nil {
		return *m.HTTPAddr
	}
	return ""
}

func (m *CreateDataNodeCommand) GetTCPAddr() string {
	if m != nil && m.TCPAddr != nil {
		return *m.TCPAddr
	}
	return ""
}

var E_CreateDataNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateDataNodeCommand)(nil),
	Field:         127,
	Name:          "internal.CreateDataNodeCommand.command",
	Tag:           "bytes,127,opt,name=command",
}

type UpdateDataNodeCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Host             *string `protobuf:"bytes,2,req,name=Host" json:"Host,omitempty"`
	TCPHost          *string `protobuf:"bytes,3,req,name=TCPHost" json:"TCPHost,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateDataNodeCommand) Reset()                    { *m = UpdateDataNodeCommand{} }
func (m *UpdateDataNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*UpdateDataNodeCommand) ProtoMessage()               {}
func (*UpdateDataNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{35} }

func (m *UpdateDataNodeCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *UpdateDataNodeCommand) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *UpdateDataNodeCommand) GetTCPHost() string {
	if m != nil && m.TCPHost != nil {
		return *m.TCPHost
	}
	return ""
}

var E_UpdateDataNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*UpdateDataNodeCommand)(nil),
	Field:         128,
	Name:          "internal.UpdateDataNodeCommand.command",
	Tag:           "bytes,128,opt,name=command",
}

type DeleteMetaNodeCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteMetaNodeCommand) Reset()                    { *m = DeleteMetaNodeCommand{} }
func (m *DeleteMetaNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*DeleteMetaNodeCommand) ProtoMessage()               {}
func (*DeleteMetaNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{36} }

func (m *DeleteMetaNodeCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

var E_DeleteMetaNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DeleteMetaNodeCommand)(nil),
	Field:         129,
	Name:          "internal.DeleteMetaNodeCommand.command",
	Tag:           "bytes,129,opt,name=command",
}

type DeleteDataNodeCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteDataNodeCommand) Reset()                    { *m = DeleteDataNodeCommand{} }
func (m *DeleteDataNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*DeleteDataNodeCommand) ProtoMessage()               {}
func (*DeleteDataNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{37} }

func (m *DeleteDataNodeCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

var E_DeleteDataNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DeleteDataNodeCommand)(nil),
	Field:         130,
	Name:          "internal.DeleteDataNodeCommand.command",
	Tag:           "bytes,130,opt,name=command",
}

// SetMetaNodeCommand is for the initial metanode in a cluster or
// if the single host restarts and its hostname changes, this will update it
type SetMetaNodeCommand struct {
	HTTPAddr         *string `protobuf:"bytes,1,req,name=HTTPAddr" json:"HTTPAddr,omitempty"`
	TCPAddr          *string `protobuf:"bytes,2,req,name=TCPAddr" json:"TCPAddr,omitempty"`
	Rand             *uint64 `protobuf:"varint,3,req,name=Rand" json:"Rand,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetMetaNodeCommand) Reset()                    { *m = SetMetaNodeCommand{} }
func (m *SetMetaNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*SetMetaNodeCommand) ProtoMessage()               {}
func (*SetMetaNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{38} }

func (m *SetMetaNodeCommand) GetHTTPAddr() string {
	if m != nil && m.HTTPAddr != nil {
		return *m.HTTPAddr
	}
	return ""
}

func (m *SetMetaNodeCommand) GetTCPAddr() string {
	if m != nil && m.TCPAddr != nil {
		return *m.TCPAddr
	}
	return ""
}

func (m *SetMetaNodeCommand) GetRand() uint64 {
	if m != nil && m.Rand != nil {
		return *m.Rand
	}
	return 0
}

var E_SetMetaNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         131,
	Name:          "internal.SetMetaNodeCommand.command",
	Tag:           "bytes,131,opt,name=command",
}

type DropShardCommand struct {
	ID               *int64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DropShardCommand) Reset()                    { *m = DropShardCommand{} }
func (m *DropShardCommand) String() string            { return proto.CompactTextString(m) }
func (*DropShardCommand) ProtoMessage()               {}
func (*DropShardCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{39} }

func (m *DropShardCommand) GetID() int64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

var E_DropShardCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         132,
	Name:          "internal.DropShardCommand.command",
	Tag:           "bytes,132,opt,name=command",
}

type SetUserPasswordCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Hash             *string `protobuf:"bytes,2,req,name=Hash" json:"Hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetUserPasswordCommand) Reset()                    { *m = SetUserPasswordCommand{} }
func (m *SetUserPasswordCommand) String() string            { return proto.CompactTextString(m) }
func (*SetUserPasswordCommand) ProtoMessage()               {}
func (*SetUserPasswordCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{40} }

func (m *SetUserPasswordCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SetUserPasswordCommand) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

var E_SetUserPasswordCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         133,
	Name:          "internal.SetUserPasswordCommand.command",
	Tag:           "bytes,133,opt,name=command",
}

type AddUserPermissionsCommand struct {
	Name             *string        `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Permissions      *UserPrivilege `protobuf:"bytes,2,req,name=Permissions" json:"Permissions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *AddUserPermissionsCommand) Reset()                    { *m = AddUserPermissionsCommand{} }
func (m *AddUserPermissionsCommand) String() string            { return proto.CompactTextString(m) }
func (*AddUserPermissionsCommand) ProtoMessage()               {}
func (*AddUserPermissionsCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{41} }

func (m *AddUserPermissionsCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *AddUserPermissionsCommand) GetPermissions() *UserPrivilege {
	if m != nil {
		return m.Permissions
	}
	return nil
}

var E_AddUserPermissionsCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         134,
	Name:          "internal.AddUserPermissionsCommand.command",
	Tag:           "bytes,134,opt,name=command",
}

type RemoveUserPermissionsCommand struct {
	Name             *string        `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Permissions      *UserPrivilege `protobuf:"bytes,2,req,name=Permissions" json:"Permissions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RemoveUserPermissionsCommand) Reset()         { *m = RemoveUserPermissionsCommand{} }
func (m *RemoveUserPermissionsCommand) String() string { return proto.CompactTextString(m) }
func (*RemoveUserPermissionsCommand) ProtoMessage()    {}
func (*RemoveUserPermissionsCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{42}
}

func (m *RemoveUserPermissionsCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RemoveUserPermissionsCommand) GetPermissions() *UserPrivilege {
	if m != nil {
		return m.Permissions
	}
	return nil
}

var E_RemoveUserPermissionsCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         135,
	Name:          "internal.RemoveUserPermissionsCommand.command",
	Tag:           "bytes,135,opt,name=command",
}

type AddShardOwnerCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	NodeID           *uint64 `protobuf:"varint,2,req,name=NodeID" json:"NodeID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddShardOwnerCommand) Reset()                    { *m = AddShardOwnerCommand{} }
func (m *AddShardOwnerCommand) String() string            { return proto.CompactTextString(m) }
func (*AddShardOwnerCommand) ProtoMessage()               {}
func (*AddShardOwnerCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{43} }

func (m *AddShardOwnerCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *AddShardOwnerCommand) GetNodeID() uint64 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

var E_AddShardOwnerCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         136,
	Name:          "internal.AddShardOwnerCommand.command",
	Tag:           "bytes,136,opt,name=command",
}

type RemoveShardOwnerCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	NodeID           *uint64 `protobuf:"varint,2,req,name=NodeID" json:"NodeID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemoveShardOwnerCommand) Reset()                    { *m = RemoveShardOwnerCommand{} }
func (m *RemoveShardOwnerCommand) String() string            { return proto.CompactTextString(m) }
func (*RemoveShardOwnerCommand) ProtoMessage()               {}
func (*RemoveShardOwnerCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{44} }

func (m *RemoveShardOwnerCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *RemoveShardOwnerCommand) GetNodeID() uint64 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

var E_RemoveShardOwnerCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         137,
	Name:          "internal.RemoveShardOwnerCommand.command",
	Tag:           "bytes,137,opt,name=command",
}

type AddPendingShardOwnerCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	NodeID           *uint64 `protobuf:"varint,2,req,name=NodeID" json:"NodeID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddPendingShardOwnerCommand) Reset()                    { *m = AddPendingShardOwnerCommand{} }
func (m *AddPendingShardOwnerCommand) String() string            { return proto.CompactTextString(m) }
func (*AddPendingShardOwnerCommand) ProtoMessage()               {}
func (*AddPendingShardOwnerCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{45} }

func (m *AddPendingShardOwnerCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *AddPendingShardOwnerCommand) GetNodeID() uint64 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

var E_AddPendingShardOwnerCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         138,
	Name:          "internal.AddPendingShardOwnerCommand.command",
	Tag:           "bytes,138,opt,name=command",
}

type RemovePendingShardOwnerCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	NodeID           *uint64 `protobuf:"varint,2,req,name=NodeID" json:"NodeID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemovePendingShardOwnerCommand) Reset()         { *m = RemovePendingShardOwnerCommand{} }
func (m *RemovePendingShardOwnerCommand) String() string { return proto.CompactTextString(m) }
func (*RemovePendingShardOwnerCommand) ProtoMessage()    {}
func (*RemovePendingShardOwnerCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{46}
}

func (m *RemovePendingShardOwnerCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *RemovePendingShardOwnerCommand) GetNodeID() uint64 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

var E_RemovePendingShardOwnerCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         139,
	Name:          "internal.RemovePendingShardOwnerCommand.command",
	Tag:           "bytes,139,opt,name=command",
}

type CommitPendingShardOwnerCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	NodeID           *uint64 `protobuf:"varint,2,req,name=NodeID" json:"NodeID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CommitPendingShardOwnerCommand) Reset()         { *m = CommitPendingShardOwnerCommand{} }
func (m *CommitPendingShardOwnerCommand) String() string { return proto.CompactTextString(m) }
func (*CommitPendingShardOwnerCommand) ProtoMessage()    {}
func (*CommitPendingShardOwnerCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{47}
}

func (m *CommitPendingShardOwnerCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *CommitPendingShardOwnerCommand) GetNodeID() uint64 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

var E_CommitPendingShardOwnerCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         140,
	Name:          "internal.CommitPendingShardOwnerCommand.command",
	Tag:           "bytes,140,opt,name=command",
}

type TruncateShardGroupCommand struct {
	TruncateAt       *uint64 `protobuf:"varint,1,req,name=TruncateAt" json:"TruncateAt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TruncateShardGroupCommand) Reset()                    { *m = TruncateShardGroupCommand{} }
func (m *TruncateShardGroupCommand) String() string            { return proto.CompactTextString(m) }
func (*TruncateShardGroupCommand) ProtoMessage()               {}
func (*TruncateShardGroupCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{48} }

func (m *TruncateShardGroupCommand) GetTruncateAt() uint64 {
	if m != nil && m.TruncateAt != nil {
		return *m.TruncateAt
	}
	return 0
}

var E_TruncateShardGroupCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         141,
	Name:          "internal.TruncateShardGroupCommand.command",
	Tag:           "bytes,141,opt,name=command",
}

type ChangeRoleNameCommand struct {
	OldName          *string `protobuf:"bytes,1,req,name=OldName" json:"OldName,omitempty"`
	NewName          *string `protobuf:"bytes,2,req,name=NewName" json:"NewName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChangeRoleNameCommand) Reset()                    { *m = ChangeRoleNameCommand{} }
func (m *ChangeRoleNameCommand) String() string            { return proto.CompactTextString(m) }
func (*ChangeRoleNameCommand) ProtoMessage()               {}
func (*ChangeRoleNameCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{49} }

func (m *ChangeRoleNameCommand) GetOldName() string {
	if m != nil && m.OldName != nil {
		return *m.OldName
	}
	return ""
}

func (m *ChangeRoleNameCommand) GetNewName() string {
	if m != nil && m.NewName != nil {
		return *m.NewName
	}
	return ""
}

var E_ChangeRoleNameCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         142,
	Name:          "internal.ChangeRoleNameCommand.command",
	Tag:           "bytes,142,opt,name=command",
}

type ImportDataCommand struct {
	Data                 []byte  `protobuf:"bytes,1,req,name=Data" json:"Data,omitempty"`
	Force                *bool   `protobuf:"varint,2,req,name=Force" json:"Force,omitempty"`
	Database             *string `protobuf:"bytes,3,req,name=Database" json:"Database,omitempty"`
	RetentionPolicy      *string `protobuf:"bytes,4,req,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	ShardId              *uint64 `protobuf:"varint,5,req,name=ShardId" json:"ShardId,omitempty"`
	NewDatabase          *string `protobuf:"bytes,6,req,name=NewDatabase" json:"NewDatabase,omitempty"`
	NewRetentionPolicy   []byte  `protobuf:"bytes,7,req,name=NewRetentionPolicy" json:"NewRetentionPolicy,omitempty"`
	NewReplicationFactor *uint64 `protobuf:"varint,8,req,name=NewReplicationFactor" json:"NewReplicationFactor,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (m *ImportDataCommand) Reset()                    { *m = ImportDataCommand{} }
func (m *ImportDataCommand) String() string            { return proto.CompactTextString(m) }
func (*ImportDataCommand) ProtoMessage()               {}
func (*ImportDataCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{50} }

func (m *ImportDataCommand) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ImportDataCommand) GetForce() bool {
	if m != nil && m.Force != nil {
		return *m.Force
	}
	return false
}

func (m *ImportDataCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *ImportDataCommand) GetRetentionPolicy() string {
	if m != nil && m.RetentionPolicy != nil {
		return *m.RetentionPolicy
	}
	return ""
}

func (m *ImportDataCommand) GetShardId() uint64 {
	if m != nil && m.ShardId != nil {
		return *m.ShardId
	}
	return 0
}

func (m *ImportDataCommand) GetNewDatabase() string {
	if m != nil && m.NewDatabase != nil {
		return *m.NewDatabase
	}
	return ""
}

func (m *ImportDataCommand) GetNewRetentionPolicy() []byte {
	if m != nil {
		return m.NewRetentionPolicy
	}
	return nil
}

func (m *ImportDataCommand) GetNewReplicationFactor() uint64 {
	if m != nil && m.NewReplicationFactor != nil {
		return *m.NewReplicationFactor
	}
	return 0
}

var E_ImportDataCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         143,
	Name:          "internal.ImportDataCommand.command",
	Tag:           "bytes,143,opt,name=command",
}

type CreateBalancedShardGroupCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Policy           []byte  `protobuf:"bytes,2,req,name=Policy" json:"Policy,omitempty"`
	Timestamp        *int64  `protobuf:"varint,3,req,name=Timestamp" json:"Timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateBalancedShardGroupCommand) Reset()         { *m = CreateBalancedShardGroupCommand{} }
func (m *CreateBalancedShardGroupCommand) String() string { return proto.CompactTextString(m) }
func (*CreateBalancedShardGroupCommand) ProtoMessage()    {}
func (*CreateBalancedShardGroupCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{51}
}

func (m *CreateBalancedShardGroupCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CreateBalancedShardGroupCommand) GetPolicy() []byte {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *CreateBalancedShardGroupCommand) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

var E_CreateBalancedShardGroupCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         144,
	Name:          "internal.CreateBalancedShardGroupCommand.command",
	Tag:           "bytes,144,opt,name=command",
}

func init() {
	proto.RegisterType((*ClusterData)(nil), "internal.ClusterData")
	proto.RegisterType((*NodeInfo)(nil), "internal.NodeInfo")
	proto.RegisterType((*RoleInfo)(nil), "internal.RoleInfo")
	proto.RegisterType((*UserInfo)(nil), "internal.UserInfo")
	proto.RegisterType((*UserPrivilege)(nil), "internal.UserPrivilege")
	proto.RegisterType((*ScopedPermission)(nil), "internal.ScopedPermission")
	proto.RegisterType((*Response)(nil), "internal.Response")
	proto.RegisterType((*Command)(nil), "internal.Command")
	proto.RegisterType((*CreateDatabaseCommand)(nil), "internal.CreateDatabaseCommand")
	proto.RegisterType((*DropDatabaseCommand)(nil), "internal.DropDatabaseCommand")
	proto.RegisterType((*CreateRetentionPolicyCommand)(nil), "internal.CreateRetentionPolicyCommand")
	proto.RegisterType((*DropRetentionPolicyCommand)(nil), "internal.DropRetentionPolicyCommand")
	proto.RegisterType((*SetDefaultRetentionPolicyCommand)(nil), "internal.SetDefaultRetentionPolicyCommand")
	proto.RegisterType((*UpdateRetentionPolicyCommand)(nil), "internal.UpdateRetentionPolicyCommand")
	proto.RegisterType((*CreateShardGroupCommand)(nil), "internal.CreateShardGroupCommand")
	proto.RegisterType((*DeleteShardGroupCommand)(nil), "internal.DeleteShardGroupCommand")
	proto.RegisterType((*CreateContinuousQueryCommand)(nil), "internal.CreateContinuousQueryCommand")
	proto.RegisterType((*DropContinuousQueryCommand)(nil), "internal.DropContinuousQueryCommand")
	proto.RegisterType((*CreateUserCommand)(nil), "internal.CreateUserCommand")
	proto.RegisterType((*DropUserCommand)(nil), "internal.DropUserCommand")
	proto.RegisterType((*UpdateUserCommand)(nil), "internal.UpdateUserCommand")
	proto.RegisterType((*SetPrivilegeCommand)(nil), "internal.SetPrivilegeCommand")
	proto.RegisterType((*CreateRoleCommand)(nil), "internal.CreateRoleCommand")
	proto.RegisterType((*DropRoleCommand)(nil), "internal.DropRoleCommand")
	proto.RegisterType((*AddRoleUsersCommand)(nil), "internal.AddRoleUsersCommand")
	proto.RegisterType((*RemoveRoleUsersCommand)(nil), "internal.RemoveRoleUsersCommand")
	proto.RegisterType((*AddRolePermissionsCommand)(nil), "internal.AddRolePermissionsCommand")
	proto.RegisterType((*RemoveRolePermissionsCommand)(nil), "internal.RemoveRolePermissionsCommand")
	proto.RegisterType((*SetDataCommand)(nil), "internal.SetDataCommand")
	proto.RegisterType((*SetAdminPrivilegeCommand)(nil), "internal.SetAdminPrivilegeCommand")
	proto.RegisterType((*CreateSubscriptionCommand)(nil), "internal.CreateSubscriptionCommand")
	proto.RegisterType((*DropSubscriptionCommand)(nil), "internal.DropSubscriptionCommand")
	proto.RegisterType((*RemovePeerCommand)(nil), "internal.RemovePeerCommand")
	proto.RegisterType((*CreateMetaNodeCommand)(nil), "internal.CreateMetaNodeCommand")
	proto.RegisterType((*CreateDataNodeCommand)(nil), "internal.CreateDataNodeCommand")
	proto.RegisterType((*UpdateDataNodeCommand)(nil), "internal.UpdateDataNodeCommand")
	proto.RegisterType((*DeleteMetaNodeCommand)(nil), "internal.DeleteMetaNodeCommand")
	proto.RegisterType((*DeleteDataNodeCommand)(nil), "internal.DeleteDataNodeCommand")
	proto.RegisterType((*SetMetaNodeCommand)(nil), "internal.SetMetaNodeCommand")
	proto.RegisterType((*DropShardCommand)(nil), "internal.DropShardCommand")
	proto.RegisterType((*SetUserPasswordCommand)(nil), "internal.SetUserPasswordCommand")
	proto.RegisterType((*AddUserPermissionsCommand)(nil), "internal.AddUserPermissionsCommand")
	proto.RegisterType((*RemoveUserPermissionsCommand)(nil), "internal.RemoveUserPermissionsCommand")
	proto.RegisterType((*AddShardOwnerCommand)(nil), "internal.AddShardOwnerCommand")
	proto.RegisterType((*RemoveShardOwnerCommand)(nil), "internal.RemoveShardOwnerCommand")
	proto.RegisterType((*AddPendingShardOwnerCommand)(nil), "internal.AddPendingShardOwnerCommand")
	proto.RegisterType((*RemovePendingShardOwnerCommand)(nil), "internal.RemovePendingShardOwnerCommand")
	proto.RegisterType((*CommitPendingShardOwnerCommand)(nil), "internal.CommitPendingShardOwnerCommand")
	proto.RegisterType((*TruncateShardGroupCommand)(nil), "internal.TruncateShardGroupCommand")
	proto.RegisterType((*ChangeRoleNameCommand)(nil), "internal.ChangeRoleNameCommand")
	proto.RegisterType((*ImportDataCommand)(nil), "internal.ImportDataCommand")
	proto.RegisterType((*CreateBalancedShardGroupCommand)(nil), "internal.CreateBalancedShardGroupCommand")
	proto.RegisterEnum("internal.Command_Type", Command_Type_name, Command_Type_value)
	proto.RegisterExtension(E_CreateDatabaseCommand_Command)
	proto.RegisterExtension(E_DropDatabaseCommand_Command)
	proto.RegisterExtension(E_CreateRetentionPolicyCommand_Command)
	proto.RegisterExtension(E_DropRetentionPolicyCommand_Command)
	proto.RegisterExtension(E_SetDefaultRetentionPolicyCommand_Command)
	proto.RegisterExtension(E_UpdateRetentionPolicyCommand_Command)
	proto.RegisterExtension(E_CreateShardGroupCommand_Command)
	proto.RegisterExtension(E_DeleteShardGroupCommand_Command)
	proto.RegisterExtension(E_CreateContinuousQueryCommand_Command)
	proto.RegisterExtension(E_DropContinuousQueryCommand_Command)
	proto.RegisterExtension(E_CreateUserCommand_Command)
	proto.RegisterExtension(E_DropUserCommand_Command)
	proto.RegisterExtension(E_UpdateUserCommand_Command)
	proto.RegisterExtension(E_SetPrivilegeCommand_Command)
	proto.RegisterExtension(E_CreateRoleCommand_Command)
	proto.RegisterExtension(E_DropRoleCommand_Command)
	proto.RegisterExtension(E_AddRoleUsersCommand_Command)
	proto.RegisterExtension(E_RemoveRoleUsersCommand_Command)
	proto.RegisterExtension(E_AddRolePermissionsCommand_Command)
	proto.RegisterExtension(E_RemoveRolePermissionsCommand_Command)
	proto.RegisterExtension(E_SetDataCommand_Command)
	proto.RegisterExtension(E_SetAdminPrivilegeCommand_Command)
	proto.RegisterExtension(E_CreateSubscriptionCommand_Command)
	proto.RegisterExtension(E_DropSubscriptionCommand_Command)
	proto.RegisterExtension(E_RemovePeerCommand_Command)
	proto.RegisterExtension(E_CreateMetaNodeCommand_Command)
	proto.RegisterExtension(E_CreateDataNodeCommand_Command)
	proto.RegisterExtension(E_UpdateDataNodeCommand_Command)
	proto.RegisterExtension(E_DeleteMetaNodeCommand_Command)
	proto.RegisterExtension(E_DeleteDataNodeCommand_Command)
	proto.RegisterExtension(E_SetMetaNodeCommand_Command)
	proto.RegisterExtension(E_DropShardCommand_Command)
	proto.RegisterExtension(E_SetUserPasswordCommand_Command)
	proto.RegisterExtension(E_AddUserPermissionsCommand_Command)
	proto.RegisterExtension(E_RemoveUserPermissionsCommand_Command)
	proto.RegisterExtension(E_AddShardOwnerCommand_Command)
	proto.RegisterExtension(E_RemoveShardOwnerCommand_Command)
	proto.RegisterExtension(E_AddPendingShardOwnerCommand_Command)
	proto.RegisterExtension(E_RemovePendingShardOwnerCommand_Command)
	proto.RegisterExtension(E_CommitPendingShardOwnerCommand_Command)
	proto.RegisterExtension(E_TruncateShardGroupCommand_Command)
	proto.RegisterExtension(E_ChangeRoleNameCommand_Command)
	proto.RegisterExtension(E_ImportDataCommand_Command)
	proto.RegisterExtension(E_CreateBalancedShardGroupCommand_Command)
}

func init() { proto.RegisterFile("internal/meta.proto", fileDescriptorMeta) }

var fileDescriptorMeta = []byte{
	// 1771 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x59, 0xeb, 0x6f, 0x1b, 0x45,
	0x10, 0xd7, 0xf9, 0x91, 0xd8, 0x13, 0x3b, 0x8f, 0x4d, 0x9a, 0x5c, 0x1e, 0x6d, 0xdc, 0x6d, 0x5a,
	0x4c, 0xa9, 0x82, 0x64, 0xf5, 0x23, 0x08, 0x85, 0xb8, 0x8f, 0x80, 0x9a, 0xba, 0xb1, 0x2b, 0xf1,
	0x01, 0x55, 0xba, 0xfa, 0x36, 0xc9, 0x15, 0xfb, 0xce, 0xdc, 0x9d, 0x9b, 0x04, 0x0a, 0x09, 0x14,
	0x4a, 0x79, 0x94, 0x22, 0x24, 0x24, 0x8a, 0xc4, 0x77, 0xfe, 0x0b, 0x04, 0x7f, 0x0f, 0x7f, 0x03,
	0x42, 0xbb, 0xe7, 0xf5, 0x9d, 0xef, 0xf6, 0xf6, 0xae, 0x8d, 0xf8, 0xd4, 0x74, 0x67, 0x76, 0x7e,
	0xbf, 0x99, 0xd9, 0x9b, 0x9d, 0x1d, 0xc3, 0xac, 0x61, 0xba, 0xc4, 0x36, 0xb5, 0xce, 0x9b, 0x5d,
	0xe2, 0x6a, 0xeb, 0x3d, 0xdb, 0x72, 0x2d, 0x54, 0xe0, 0x8b, 0xf8, 0x6f, 0x05, 0x26, 0x36, 0x3b,
	0x7d, 0xc7, 0x25, 0x76, 0x5d, 0x73, 0x35, 0x54, 0x82, 0x1c, 0xfd, 0x57, 0x55, 0x2a, 0x99, 0x6a,
	0x09, 0xcd, 0x40, 0xf1, 0x96, 0x76, 0xb8, 0x6d, 0xe9, 0x64, 0xab, 0xae, 0x66, 0x2a, 0x99, 0x6a,
	0x0e, 0x5d, 0x84, 0x22, 0x55, 0xa0, 0x6b, 0x8e, 0x9a, 0xad, 0x64, 0xab, 0x13, 0x35, 0xb4, 0xce,
	0xcd, 0xad, 0x33, 0x55, 0x73, 0xd7, 0xa2, 0x6a, 0xb7, 0x08, 0x57, 0xcb, 0xc5, 0xaa, 0x9d, 0x87,
	0xfc, 0x8e, 0xd5, 0x21, 0x8e, 0x9a, 0x0f, 0xab, 0xd0, 0x65, 0xae, 0x72, 0xd7, 0x21, 0xb6, 0xa3,
	0x8e, 0x85, 0x55, 0xe8, 0x32, 0x55, 0xc1, 0x77, 0xa0, 0x30, 0xb4, 0x08, 0x90, 0xd9, 0xaa, 0x33,
	0xfa, 0x39, 0xea, 0xcc, 0x4d, 0xcb, 0x71, 0x19, 0xf3, 0x22, 0x9a, 0x82, 0xf1, 0xd6, 0x66, 0x83,
	0x2d, 0x64, 0x2b, 0x4a, 0xb5, 0x88, 0x96, 0x00, 0x35, 0x88, 0xa9, 0x1b, 0xe6, 0x5e, 0x73, 0x5f,
	0xb3, 0xf5, 0xdb, 0x07, 0x26, 0x85, 0xa1, 0x64, 0x73, 0xd8, 0x80, 0xc2, 0x90, 0x41, 0x09, 0x72,
	0xdb, 0x5a, 0x97, 0x30, 0xa3, 0x45, 0x74, 0x05, 0x26, 0x1a, 0xc4, 0xee, 0x1a, 0x8e, 0x63, 0x58,
	0xa6, 0xc3, 0x6c, 0x4f, 0xd4, 0x16, 0x46, 0x59, 0x35, 0x6c, 0xe3, 0xa1, 0xd1, 0x21, 0x7b, 0xc4,
	0x67, 0x9f, 0x65, 0x7a, 0x22, 0xf6, 0x2d, 0x28, 0xf0, 0xbf, 0x43, 0x50, 0x94, 0xbf, 0xe6, 0xec,
	0x0f, 0xf8, 0x87, 0x80, 0xbd, 0xd8, 0xc7, 0x01, 0xe3, 0xab, 0x50, 0x1e, 0x65, 0x32, 0x0d, 0x05,
	0x9a, 0xb8, 0xfb, 0x9a, 0xc3, 0xcd, 0xcf, 0x40, 0x71, 0x28, 0x66, 0x18, 0x79, 0xdc, 0x84, 0xe9,
	0x66, 0xdb, 0xea, 0x11, 0xdd, 0x47, 0xa2, 0x6a, 0x3b, 0xc4, 0xb1, 0xfa, 0x76, 0x9b, 0x38, 0x83,
	0x73, 0xf1, 0x52, 0x31, 0xc0, 0x57, 0xa1, 0xb0, 0x43, 0x9c, 0x9e, 0x65, 0x3a, 0x84, 0xa6, 0xe7,
	0xf6, 0xfb, 0xcc, 0x4a, 0x01, 0x95, 0x21, 0x7f, 0xcd, 0xb6, 0x2d, 0x5b, 0xcd, 0xb0, 0x74, 0x94,
	0x21, 0xbf, 0x65, 0xea, 0xe4, 0x90, 0x65, 0x27, 0x87, 0xff, 0x00, 0x18, 0xdf, 0xb4, 0xba, 0x5d,
	0xcd, 0xd4, 0xd1, 0x1a, 0xe4, 0xdc, 0xa3, 0x9e, 0xc7, 0x7b, 0xb2, 0x36, 0xef, 0x03, 0x0d, 0x14,
	0xd6, 0x5b, 0x47, 0x3d, 0x82, 0xff, 0x29, 0x42, 0x8e, 0xfe, 0x81, 0x16, 0xe1, 0xcc, 0xa6, 0x4d,
	0x34, 0x97, 0x70, 0x87, 0x07, 0x6a, 0xd3, 0x0a, 0x5a, 0x80, 0xd9, 0xba, 0x6d, 0xf5, 0xc2, 0x82,
	0x0c, 0xaa, 0xc0, 0x8a, 0xb7, 0x67, 0x87, 0xb8, 0xc4, 0x74, 0x0d, 0xcb, 0x6c, 0x58, 0x1d, 0xa3,
	0x7d, 0xc4, 0x35, 0xb2, 0xe8, 0x1c, 0x2c, 0xd1, 0xad, 0x31, 0xf2, 0x1c, 0x5a, 0x83, 0x4a, 0x93,
	0xb8, 0x75, 0xb2, 0xab, 0xf5, 0x3b, 0x6e, 0x8c, 0x56, 0x9e, 0xe2, 0xdc, 0xed, 0xe9, 0xf1, 0x38,
	0x63, 0x68, 0x19, 0x16, 0x3c, 0x26, 0xec, 0x54, 0xde, 0xb0, 0xad, 0x7e, 0x8f, 0x0b, 0xc7, 0xa9,
	0xb0, 0x4e, 0x3a, 0x44, 0x24, 0x2c, 0xf8, 0x3e, 0x6c, 0x5a, 0xa6, 0x6b, 0x98, 0x7d, 0xab, 0xef,
	0xdc, 0xe9, 0x13, 0x7b, 0x68, 0xbb, 0xc8, 0x7d, 0x88, 0x91, 0x03, 0x3a, 0x03, 0x33, 0x9e, 0x05,
	0x9a, 0x41, 0xbe, 0x3c, 0x81, 0x66, 0x61, 0x8a, 0x6e, 0x0b, 0x2e, 0x96, 0xa8, 0xae, 0xe7, 0x49,
	0x70, 0xb9, 0x4c, 0x23, 0xdc, 0x24, 0xee, 0x30, 0xfb, 0x5c, 0x30, 0xe9, 0xdb, 0xa6, 0x1f, 0x16,
	0x5f, 0x9e, 0xe2, 0xb6, 0x83, 0x8b, 0xd3, 0xd4, 0xc8, 0x86, 0xae, 0xd3, 0x35, 0xf6, 0xf5, 0x70,
	0xc1, 0x0c, 0x5a, 0x82, 0xf9, 0x1d, 0xd2, 0xb5, 0x1e, 0x92, 0x88, 0x0c, 0xa1, 0xb3, 0xb0, 0x38,
	0xd8, 0x14, 0x38, 0x9c, 0x5c, 0x3c, 0x4b, 0xa3, 0xe3, 0x6f, 0x15, 0x68, 0xcc, 0x21, 0x04, 0x93,
	0x34, 0x83, 0x9a, 0xab, 0xf1, 0xb5, 0x33, 0x68, 0x05, 0xd4, 0x26, 0x71, 0x37, 0xf4, 0xae, 0x61,
	0x46, 0x7c, 0x9a, 0xa7, 0x90, 0x83, 0x5c, 0xf5, 0xef, 0x3b, 0x6d, 0xdb, 0xe8, 0xd1, 0x84, 0x72,
	0xf1, 0x02, 0xcb, 0x96, 0x6d, 0xf5, 0x44, 0x42, 0x95, 0xc6, 0xc3, 0xe3, 0xd3, 0x20, 0x7e, 0xfc,
	0x16, 0xfd, 0xc3, 0xcb, 0xeb, 0x27, 0x17, 0x2d, 0x8d, 0x9e, 0xeb, 0xa0, 0x68, 0x99, 0x8a, 0xbc,
	0x64, 0x84, 0x45, 0x2b, 0x54, 0xe4, 0x1d, 0x99, 0xb0, 0xc1, 0xb3, 0xbe, 0x28, 0xbc, 0xeb, 0x1c,
	0x9a, 0x07, 0xd4, 0x24, 0x6e, 0x78, 0xcb, 0x2a, 0x9a, 0x83, 0x69, 0xe6, 0x12, 0x3d, 0x7e, 0x7c,
	0xb5, 0x42, 0x7d, 0xd9, 0xea, 0xf6, 0x2c, 0x7b, 0x24, 0x78, 0xe7, 0x69, 0xb6, 0x9a, 0xc4, 0x65,
	0xd5, 0x40, 0x73, 0x9c, 0x03, 0xcb, 0xdf, 0x82, 0x07, 0xd9, 0x62, 0xb2, 0x68, 0x2e, 0x2e, 0xf8,
	0xd9, 0x8a, 0xd1, 0x58, 0x43, 0x2a, 0xcc, 0x6d, 0xe8, 0xba, 0x5f, 0xba, 0xb9, 0xe4, 0x22, 0x0d,
	0xbb, 0xb7, 0x37, 0x2a, 0xbc, 0x84, 0x56, 0x61, 0x79, 0x43, 0xd7, 0x23, 0x85, 0x9f, 0x2b, 0xbc,
	0x86, 0x30, 0x9c, 0xa3, 0xff, 0x31, 0xdc, 0x58, 0x9d, 0x2a, 0xd5, 0xe1, 0xb9, 0x8b, 0xd1, 0x79,
	0x9d, 0x7e, 0x6b, 0x2d, 0xbb, 0x6f, 0xb6, 0x47, 0xbe, 0xe4, 0x21, 0xff, 0xcb, 0x2c, 0x9b, 0xfb,
	0x9a, 0xb9, 0xc7, 0xce, 0x23, 0xad, 0xfa, 0x5c, 0xf4, 0x06, 0xba, 0x00, 0xab, 0x5e, 0xa2, 0xdf,
	0xd5, 0x3a, 0x9a, 0xd9, 0x26, 0x7a, 0xf4, 0x6b, 0xbf, 0x72, 0xb9, 0x50, 0xd0, 0xa7, 0x4f, 0x4e,
	0x4e, 0x4e, 0x32, 0xf8, 0xb1, 0x12, 0x53, 0xf0, 0x42, 0xf7, 0xc9, 0x02, 0x4c, 0x85, 0xaa, 0x0e,
	0x2b, 0xbd, 0xa5, 0xda, 0x26, 0x8c, 0xb7, 0x07, 0x3b, 0x66, 0x22, 0xc5, 0x55, 0x25, 0x15, 0xa5,
	0x3a, 0x51, 0x5b, 0x0d, 0x08, 0x44, 0x58, 0x78, 0x57, 0x58, 0x5a, 0x47, 0x29, 0xd4, 0x36, 0xa4,
	0x48, 0xbb, 0x0c, 0xe9, 0xac, 0x2f, 0x10, 0x18, 0xc4, 0xbf, 0x28, 0xf2, 0x52, 0x2d, 0xb8, 0xe9,
	0x84, 0x8e, 0x67, 0xaa, 0xa5, 0xda, 0x7b, 0x52, 0x3a, 0x7b, 0x8c, 0xce, 0xa5, 0xb0, 0xe3, 0x62,
	0x58, 0xfc, 0x44, 0x91, 0x5d, 0x10, 0x02, 0x56, 0x3c, 0x32, 0xec, 0x7a, 0xaf, 0xdd, 0x94, 0x52,
	0xd9, 0x67, 0x54, 0xd6, 0x46, 0x23, 0x13, 0x43, 0xe4, 0x67, 0x25, 0xf9, 0x26, 0x4a, 0xa4, 0xb3,
	0x2d, 0xa5, 0x63, 0x30, 0x3a, 0x97, 0x7d, 0x41, 0x12, 0x1e, 0xfe, 0x53, 0x91, 0x5f, 0x7c, 0x49,
	0x84, 0x68, 0xfb, 0xb6, 0x4d, 0x0e, 0xd8, 0x82, 0xd7, 0xbe, 0xd1, 0x0d, 0x7d, 0x5b, 0xa3, 0x96,
	0xd4, 0x5c, 0x45, 0xa9, 0x66, 0xe9, 0xca, 0x0e, 0xe9, 0x75, 0x8c, 0xb6, 0xb6, 0xad, 0xe6, 0x2b,
	0x4a, 0xb5, 0x9c, 0x90, 0xdf, 0x07, 0xe1, 0xfc, 0xca, 0x08, 0xd2, 0x73, 0x17, 0x77, 0x31, 0x0b,
	0xc8, 0x4f, 0xc2, 0x58, 0xe0, 0xa4, 0xb1, 0x66, 0xab, 0x65, 0x74, 0x89, 0xe3, 0x6a, 0xdd, 0x1e,
	0x6b, 0x06, 0xb3, 0xb5, 0x6b, 0x52, 0x72, 0x1f, 0x31, 0x72, 0xe7, 0xc3, 0x87, 0x2f, 0x82, 0x8d,
	0x7f, 0x55, 0x62, 0x7b, 0x82, 0x14, 0xbc, 0xe6, 0xa0, 0xe4, 0x6f, 0xdb, 0xaa, 0x33, 0x6a, 0xb9,
	0x04, 0x6a, 0x9d, 0x30, 0xb5, 0x18, 0x78, 0xfc, 0x42, 0x91, 0x77, 0x24, 0x89, 0x49, 0x2f, 0x43,
	0x9e, 0xe9, 0x33, 0x5a, 0xc5, 0x84, 0x74, 0x76, 0xc5, 0x9f, 0xab, 0x18, 0x7a, 0xf8, 0xb9, 0xbe,
	0x1a, 0xb3, 0x84, 0xcf, 0xd5, 0x14, 0x7d, 0xae, 0x31, 0x44, 0x8e, 0x05, 0x3d, 0x97, 0xf4, 0x21,
	0x50, 0x86, 0x3c, 0xeb, 0x47, 0x58, 0x50, 0x0a, 0xb5, 0x77, 0xa4, 0x4c, 0x2c, 0xc6, 0x64, 0x39,
	0x1c, 0x94, 0x00, 0x16, 0xbe, 0x17, 0xe9, 0xee, 0x42, 0x45, 0xfb, 0x6d, 0x29, 0x42, 0x8f, 0x21,
	0x2c, 0x8e, 0xfa, 0x1a, 0xb4, 0xdf, 0x13, 0x34, 0x8a, 0x32, 0x07, 0x13, 0x3c, 0xfa, 0x38, 0xec,
	0x51, 0xc4, 0x38, 0x7e, 0xae, 0x08, 0x9b, 0x50, 0x9a, 0x54, 0xaa, 0x66, 0xfa, 0xc0, 0xc1, 0x34,
	0x67, 0xa2, 0xaf, 0x22, 0x1a, 0xe1, 0x7c, 0xc2, 0xa5, 0x65, 0x87, 0x2f, 0x2d, 0x01, 0x32, 0x6e,
	0x09, 0x9a, 0xdf, 0x04, 0x3f, 0x1d, 0x71, 0xe6, 0x02, 0x06, 0x70, 0x23, 0xd2, 0x3b, 0x27, 0xe4,
	0xca, 0x15, 0xe5, 0x2a, 0x68, 0xf1, 0x03, 0x61, 0xe3, 0x9d, 0x10, 0x81, 0x7e, 0x38, 0x02, 0x02,
	0x13, 0xf8, 0x5e, 0x5c, 0xe7, 0x5e, 0xab, 0x4b, 0x8d, 0x3f, 0x64, 0xc6, 0x2b, 0x81, 0xc9, 0x80,
	0xd0, 0x0a, 0xd6, 0x25, 0xdd, 0x7f, 0xed, 0x86, 0x14, 0xe2, 0x80, 0x41, 0x5c, 0x88, 0xf0, 0x8f,
	0x1a, 0xc2, 0x0f, 0xe4, 0x8f, 0x88, 0x84, 0x0a, 0x75, 0x18, 0xae, 0x50, 0x32, 0x5b, 0xf8, 0xc3,
	0xf0, 0x73, 0x64, 0x74, 0x3a, 0x53, 0x7b, 0x4b, 0x8a, 0x75, 0xc4, 0xb0, 0xd4, 0xd1, 0x2b, 0xda,
	0xb7, 0x45, 0x9b, 0xc6, 0xd8, 0x97, 0x8d, 0xe0, 0x43, 0x19, 0x16, 0x9d, 0x0c, 0x2b, 0x3a, 0xd7,
	0xa5, 0xd8, 0x9f, 0x30, 0x6c, 0x3c, 0x82, 0x2d, 0x04, 0xc2, 0x7f, 0x29, 0x92, 0x17, 0x54, 0xa8,
	0x48, 0x44, 0xbf, 0x55, 0x41, 0x5f, 0x97, 0xe5, 0xf5, 0xe4, 0x96, 0xa5, 0x13, 0x35, 0xc7, 0xef,
	0xb8, 0x3a, 0x71, 0x5c, 0xc3, 0x64, 0xcd, 0x82, 0x37, 0x6c, 0x2a, 0x26, 0x9c, 0x89, 0x4f, 0xc3,
	0x67, 0x22, 0x96, 0x25, 0xbd, 0xe5, 0xe2, 0x9e, 0x79, 0xaf, 0xec, 0x41, 0xc2, 0x0d, 0xfc, 0x28,
	0x72, 0x03, 0x8b, 0xf1, 0xb1, 0x29, 0x78, 0x64, 0x0e, 0x67, 0x64, 0x8a, 0x37, 0x23, 0xdb, 0xd0,
	0x75, 0x3b, 0x55, 0xe5, 0xfd, 0x2c, 0x5c, 0x91, 0x22, 0xa6, 0xf1, 0x33, 0x25, 0xe6, 0xf9, 0x4a,
	0x7d, 0xbf, 0xd9, 0x6a, 0x35, 0x18, 0x98, 0x12, 0x18, 0xc8, 0xf9, 0xe8, 0x94, 0xcb, 0x0e, 0xc5,
	0xf1, 0x7a, 0x10, 0xf9, 0xa3, 0xe4, 0x73, 0xf1, 0xa3, 0x24, 0x84, 0x8a, 0x8f, 0x63, 0x9e, 0xcc,
	0x29, 0xe8, 0x24, 0x10, 0x38, 0x8e, 0x7f, 0x15, 0x05, 0x09, 0x3c, 0x55, 0x62, 0x5e, 0xe6, 0x69,
	0x27, 0x95, 0x94, 0x89, 0xbc, 0x42, 0x9e, 0x28, 0x61, 0x2a, 0x42, 0x40, 0x6c, 0xc4, 0x0c, 0x02,
	0x82, 0x4c, 0x12, 0xa0, 0xbe, 0x88, 0x40, 0x09, 0x2d, 0xfa, 0x50, 0x12, 0xa7, 0x13, 0xa0, 0xbe,
	0x8c, 0x81, 0x12, 0x04, 0x58, 0x30, 0xa9, 0x78, 0xf9, 0xe3, 0x26, 0xbf, 0xe2, 0x1e, 0x7b, 0x6c,
	0x56, 0x46, 0x4a, 0x5a, 0xd8, 0x6b, 0x2d, 0x3a, 0x1b, 0x09, 0x38, 0x9c, 0x4d, 0x80, 0xf8, 0x2a,
	0x0d, 0xc4, 0x41, 0xdc, 0x44, 0x45, 0xda, 0x50, 0xc9, 0x81, 0xbf, 0x4e, 0x03, 0xfc, 0x9b, 0x22,
	0x99, 0xd7, 0x9c, 0x66, 0x44, 0x9e, 0x40, 0xee, 0x49, 0x1a, 0x72, 0xbf, 0x2b, 0xf2, 0x69, 0xd1,
	0xff, 0xc8, 0xef, 0x9b, 0x34, 0xfc, 0xfa, 0xe2, 0x51, 0xd5, 0x48, 0x09, 0x98, 0x84, 0xb1, 0xe0,
	0x0f, 0x2d, 0x09, 0xb0, 0x4f, 0xd3, 0xc0, 0x1e, 0xc6, 0xce, 0xc1, 0x4e, 0x81, 0xfc, 0x6d, 0x1a,
	0xe4, 0x47, 0xd2, 0x21, 0xdb, 0x29, 0xd0, 0xbf, 0x4b, 0x83, 0x7e, 0x9c, 0x34, 0x9d, 0x3b, 0x05,
	0x81, 0xef, 0x53, 0x12, 0x90, 0x8f, 0x10, 0x4f, 0x41, 0xe0, 0x87, 0x34, 0x04, 0x6c, 0x58, 0x8c,
	0xce, 0x1e, 0x39, 0x36, 0x02, 0xe0, 0xc2, 0x0d, 0x77, 0x50, 0x8b, 0xe5, 0x98, 0xcf, 0xd2, 0xe5,
	0x5c, 0x3c, 0xcf, 0xa4, 0x85, 0xf7, 0x76, 0x47, 0x0f, 0x7c, 0x7f, 0x81, 0x51, 0x4e, 0x9a, 0xfa,
	0xf4, 0x63, 0x1a, 0xf4, 0x7f, 0x15, 0xc1, 0x08, 0x3a, 0xf4, 0x73, 0x66, 0x19, 0xf2, 0xd7, 0x2d,
	0xbb, 0xed, 0xa1, 0x16, 0x46, 0xba, 0xb1, 0x6c, 0x5c, 0x37, 0x96, 0xe3, 0x8c, 0x59, 0x1c, 0xb7,
	0x74, 0x35, 0xcf, 0x72, 0x36, 0x0b, 0x13, 0xdb, 0xe4, 0x60, 0xb8, 0x7d, 0x8c, 0x69, 0x2d, 0x01,
	0xda, 0x26, 0x07, 0x61, 0x0b, 0xe3, 0x0c, 0x7b, 0x05, 0xe6, 0x98, 0x8c, 0x8d, 0xa7, 0xa8, 0xf4,
	0xba, 0xd6, 0x76, 0x2d, 0x5b, 0x2d, 0xa4, 0x08, 0xff, 0xf3, 0x34, 0x01, 0x78, 0xa1, 0x24, 0x0e,
	0x8d, 0x13, 0xc7, 0x41, 0x25, 0xd1, 0x98, 0x4a, 0xce, 0xed, 0xa7, 0x14, 0xdc, 0xfe, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0x2f, 0x34, 0x07, 0xe9, 0x85, 0x1e, 0x00, 0x00,
}
