// Code generated by protoc-gen-gogo.
// source: internal/data.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal/data.proto

It has these top-level messages:
	CopyShardRequest
	CopyShardResponse
	CopyShardStatusRequest
	CopyShardStatusResponse
	CopyShardStatus
	KillCopyShardRequest
	KillCopyShardResponse
	RemoveShardRequest
	RemoveShardResponse
	JoinClusterRequest
	JoinClusterResponse
	LeaveClusterRequest
	LeaveClusterResponse
	WriteShardRequest
	WriteShardResponse
	ExecuteStatementRequest
	ExecuteStatementResponse
	CreateIteratorRequest
	CreateIteratorResponse
	IteratorStats
	FieldDimensionsRequest
	Field
	FieldDimensionsResponse
	ExpandSourcesRequest
	ExpandSourcesResponse
	DownloadShardSnapshotRequest
	DownloadShardSnapshotResponse
	ShardStatusRequest
	ShardStatusResponse
	CreateShardSnapshotRequest
	CreateShardSnapshotResponse
	DeleteShardSnapshotRequest
	DeleteShardSnapshotResponse
	QueryInfo
	ShowQueriesRequest
	ShowQueriesResponse
	KillQueryRequest
	KillQueryResponse
	RestoreShardRequest
	RestoreShardResponse
	ShowMeasurementsRequest
	ShowMeasurementsResponse
	KeyValue
	TagValues
	ShowTagValuesRequest
	ShowTagValuesResponse
*/
package internal

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CopyShardRequest struct {
	Source           *string `protobuf:"bytes,1,req,name=Source" json:"Source,omitempty"`
	Dest             *string `protobuf:"bytes,2,req,name=Dest" json:"Dest,omitempty"`
	Database         *string `protobuf:"bytes,3,opt,name=Database" json:"Database,omitempty"`
	Policy           *string `protobuf:"bytes,4,req,name=Policy" json:"Policy,omitempty"`
	ShardID          *uint64 `protobuf:"varint,5,req,name=ShardID" json:"ShardID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CopyShardRequest) Reset()                    { *m = CopyShardRequest{} }
func (m *CopyShardRequest) String() string            { return proto.CompactTextString(m) }
func (*CopyShardRequest) ProtoMessage()               {}
func (*CopyShardRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{0} }

func (m *CopyShardRequest) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *CopyShardRequest) GetDest() string {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return ""
}

func (m *CopyShardRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CopyShardRequest) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *CopyShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

type CopyShardResponse struct {
	Err              *string `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CopyShardResponse) Reset()                    { *m = CopyShardResponse{} }
func (m *CopyShardResponse) String() string            { return proto.CompactTextString(m) }
func (*CopyShardResponse) ProtoMessage()               {}
func (*CopyShardResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{1} }

func (m *CopyShardResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type CopyShardStatusRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CopyShardStatusRequest) Reset()                    { *m = CopyShardStatusRequest{} }
func (m *CopyShardStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*CopyShardStatusRequest) ProtoMessage()               {}
func (*CopyShardStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{2} }

type CopyShardStatusResponse struct {
	Err              *string `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	Tasks            *string `protobuf:"bytes,2,req,name=Tasks" json:"Tasks,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CopyShardStatusResponse) Reset()                    { *m = CopyShardStatusResponse{} }
func (m *CopyShardStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*CopyShardStatusResponse) ProtoMessage()               {}
func (*CopyShardStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{3} }

func (m *CopyShardStatusResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *CopyShardStatusResponse) GetTasks() string {
	if m != nil && m.Tasks != nil {
		return *m.Tasks
	}
	return ""
}

type CopyShardStatus struct {
	Source           *string `protobuf:"bytes,1,req,name=Source" json:"Source,omitempty"`
	Dest             *string `protobuf:"bytes,2,req,name=Dest" json:"Dest,omitempty"`
	Database         *string `protobuf:"bytes,3,req,name=Database" json:"Database,omitempty"`
	Policy           *string `protobuf:"bytes,4,req,name=Policy" json:"Policy,omitempty"`
	TotalSize        *uint64 `protobuf:"varint,5,req,name=TotalSize" json:"TotalSize,omitempty"`
	CurrentSize      *uint64 `protobuf:"varint,6,req,name=currentSize" json:"currentSize,omitempty"`
	StartedAt        *uint64 `protobuf:"varint,7,req,name=StartedAt" json:"StartedAt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CopyShardStatus) Reset()                    { *m = CopyShardStatus{} }
func (m *CopyShardStatus) String() string            { return proto.CompactTextString(m) }
func (*CopyShardStatus) ProtoMessage()               {}
func (*CopyShardStatus) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{4} }

func (m *CopyShardStatus) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *CopyShardStatus) GetDest() string {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return ""
}

func (m *CopyShardStatus) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CopyShardStatus) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *CopyShardStatus) GetTotalSize() uint64 {
	if m != nil && m.TotalSize != nil {
		return *m.TotalSize
	}
	return 0
}

func (m *CopyShardStatus) GetCurrentSize() uint64 {
	if m != nil && m.CurrentSize != nil {
		return *m.CurrentSize
	}
	return 0
}

func (m *CopyShardStatus) GetStartedAt() uint64 {
	if m != nil && m.StartedAt != nil {
		return *m.StartedAt
	}
	return 0
}

type KillCopyShardRequest struct {
	Source           *string `protobuf:"bytes,1,req,name=Source" json:"Source,omitempty"`
	Dest             *string `protobuf:"bytes,2,req,name=Dest" json:"Dest,omitempty"`
	ShardID          *uint64 `protobuf:"varint,3,req,name=ShardID" json:"ShardID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KillCopyShardRequest) Reset()                    { *m = KillCopyShardRequest{} }
func (m *KillCopyShardRequest) String() string            { return proto.CompactTextString(m) }
func (*KillCopyShardRequest) ProtoMessage()               {}
func (*KillCopyShardRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{5} }

func (m *KillCopyShardRequest) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *KillCopyShardRequest) GetDest() string {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return ""
}

func (m *KillCopyShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

type KillCopyShardResponse struct {
	Err              *string `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KillCopyShardResponse) Reset()                    { *m = KillCopyShardResponse{} }
func (m *KillCopyShardResponse) String() string            { return proto.CompactTextString(m) }
func (*KillCopyShardResponse) ProtoMessage()               {}
func (*KillCopyShardResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{6} }

func (m *KillCopyShardResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type RemoveShardRequest struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Policy           *string `protobuf:"bytes,2,req,name=Policy" json:"Policy,omitempty"`
	ShardID          *uint64 `protobuf:"varint,3,req,name=ShardID" json:"ShardID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemoveShardRequest) Reset()                    { *m = RemoveShardRequest{} }
func (m *RemoveShardRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveShardRequest) ProtoMessage()               {}
func (*RemoveShardRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{7} }

func (m *RemoveShardRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *RemoveShardRequest) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *RemoveShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

type RemoveShardResponse struct {
	Err              *string `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemoveShardResponse) Reset()                    { *m = RemoveShardResponse{} }
func (m *RemoveShardResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveShardResponse) ProtoMessage()               {}
func (*RemoveShardResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{8} }

func (m *RemoveShardResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type JoinClusterRequest struct {
	NodeId           *uint64 `protobuf:"varint,1,req,name=NodeId" json:"NodeId,omitempty"`
	NodeAddr         *string `protobuf:"bytes,2,req,name=NodeAddr" json:"NodeAddr,omitempty"`
	MetaAddrs        *string `protobuf:"bytes,3,req,name=MetaAddrs" json:"MetaAddrs,omitempty"`
	ImportMetaData   *string `protobuf:"bytes,4,req,name=ImportMetaData" json:"ImportMetaData,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *JoinClusterRequest) Reset()                    { *m = JoinClusterRequest{} }
func (m *JoinClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinClusterRequest) ProtoMessage()               {}
func (*JoinClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{9} }

func (m *JoinClusterRequest) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *JoinClusterRequest) GetNodeAddr() string {
	if m != nil && m.NodeAddr != nil {
		return *m.NodeAddr
	}
	return ""
}

func (m *JoinClusterRequest) GetMetaAddrs() string {
	if m != nil && m.MetaAddrs != nil {
		return *m.MetaAddrs
	}
	return ""
}

func (m *JoinClusterRequest) GetImportMetaData() string {
	if m != nil && m.ImportMetaData != nil {
		return *m.ImportMetaData
	}
	return ""
}

type JoinClusterResponse struct {
	NodeID           *uint64 `protobuf:"varint,1,req,name=NodeID" json:"NodeID,omitempty"`
	TCPHost          *string `protobuf:"bytes,2,req,name=TCPHost" json:"TCPHost,omitempty"`
	Err              *string `protobuf:"bytes,3,req,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *JoinClusterResponse) Reset()                    { *m = JoinClusterResponse{} }
func (m *JoinClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinClusterResponse) ProtoMessage()               {}
func (*JoinClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{10} }

func (m *JoinClusterResponse) GetNodeID() uint64 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

func (m *JoinClusterResponse) GetTCPHost() string {
	if m != nil && m.TCPHost != nil {
		return *m.TCPHost
	}
	return ""
}

func (m *JoinClusterResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type LeaveClusterRequest struct {
	NodeAddr         *string `protobuf:"bytes,1,req,name=NodeAddr" json:"NodeAddr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LeaveClusterRequest) Reset()                    { *m = LeaveClusterRequest{} }
func (m *LeaveClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*LeaveClusterRequest) ProtoMessage()               {}
func (*LeaveClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{11} }

func (m *LeaveClusterRequest) GetNodeAddr() string {
	if m != nil && m.NodeAddr != nil {
		return *m.NodeAddr
	}
	return ""
}

type LeaveClusterResponse struct {
	Err              *string `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LeaveClusterResponse) Reset()                    { *m = LeaveClusterResponse{} }
func (m *LeaveClusterResponse) String() string            { return proto.CompactTextString(m) }
func (*LeaveClusterResponse) ProtoMessage()               {}
func (*LeaveClusterResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{12} }

func (m *LeaveClusterResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type WriteShardRequest struct {
	ShardID          *uint64  `protobuf:"varint,1,req,name=ShardID" json:"ShardID,omitempty"`
	Points           [][]byte `protobuf:"bytes,2,rep,name=Points" json:"Points,omitempty"`
	Database         *string  `protobuf:"bytes,3,opt,name=Database" json:"Database,omitempty"`
	RetentionPolicy  *string  `protobuf:"bytes,4,opt,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *WriteShardRequest) Reset()                    { *m = WriteShardRequest{} }
func (m *WriteShardRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteShardRequest) ProtoMessage()               {}
func (*WriteShardRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{13} }

func (m *WriteShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *WriteShardRequest) GetPoints() [][]byte {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *WriteShardRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *WriteShardRequest) GetRetentionPolicy() string {
	if m != nil && m.RetentionPolicy != nil {
		return *m.RetentionPolicy
	}
	return ""
}

type WriteShardResponse struct {
	Code             *int32  `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WriteShardResponse) Reset()                    { *m = WriteShardResponse{} }
func (m *WriteShardResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteShardResponse) ProtoMessage()               {}
func (*WriteShardResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{14} }

func (m *WriteShardResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *WriteShardResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type ExecuteStatementRequest struct {
	Statement        *string `protobuf:"bytes,1,req,name=Statement" json:"Statement,omitempty"`
	Database         *string `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExecuteStatementRequest) Reset()                    { *m = ExecuteStatementRequest{} }
func (m *ExecuteStatementRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteStatementRequest) ProtoMessage()               {}
func (*ExecuteStatementRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{15} }

func (m *ExecuteStatementRequest) GetStatement() string {
	if m != nil && m.Statement != nil {
		return *m.Statement
	}
	return ""
}

func (m *ExecuteStatementRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

type ExecuteStatementResponse struct {
	Code             *int32  `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExecuteStatementResponse) Reset()                    { *m = ExecuteStatementResponse{} }
func (m *ExecuteStatementResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteStatementResponse) ProtoMessage()               {}
func (*ExecuteStatementResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{16} }

func (m *ExecuteStatementResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *ExecuteStatementResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type CreateIteratorRequest struct {
	ShardIDs         []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Opt              []byte   `protobuf:"bytes,2,req,name=Opt" json:"Opt,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CreateIteratorRequest) Reset()                    { *m = CreateIteratorRequest{} }
func (m *CreateIteratorRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateIteratorRequest) ProtoMessage()               {}
func (*CreateIteratorRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{17} }

func (m *CreateIteratorRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *CreateIteratorRequest) GetOpt() []byte {
	if m != nil {
		return m.Opt
	}
	return nil
}

type CreateIteratorResponse struct {
	Err              *string `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateIteratorResponse) Reset()                    { *m = CreateIteratorResponse{} }
func (m *CreateIteratorResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateIteratorResponse) ProtoMessage()               {}
func (*CreateIteratorResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{18} }

func (m *CreateIteratorResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type IteratorStats struct {
	SeriesN          *uint64 `protobuf:"varint,1,req,name=SeriesN" json:"SeriesN,omitempty"`
	PointN           []byte  `protobuf:"bytes,2,req,name=PointN" json:"PointN,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IteratorStats) Reset()                    { *m = IteratorStats{} }
func (m *IteratorStats) String() string            { return proto.CompactTextString(m) }
func (*IteratorStats) ProtoMessage()               {}
func (*IteratorStats) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{19} }

func (m *IteratorStats) GetSeriesN() uint64 {
	if m != nil && m.SeriesN != nil {
		return *m.SeriesN
	}
	return 0
}

func (m *IteratorStats) GetPointN() []byte {
	if m != nil {
		return m.PointN
	}
	return nil
}

type FieldDimensionsRequest struct {
	ShardIDs         []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Sources          []byte   `protobuf:"bytes,2,req,name=Sources" json:"Sources,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FieldDimensionsRequest) Reset()                    { *m = FieldDimensionsRequest{} }
func (m *FieldDimensionsRequest) String() string            { return proto.CompactTextString(m) }
func (*FieldDimensionsRequest) ProtoMessage()               {}
func (*FieldDimensionsRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{20} }

func (m *FieldDimensionsRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *FieldDimensionsRequest) GetSources() []byte {
	if m != nil {
		return m.Sources
	}
	return nil
}

type Field struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Type             *uint64 `protobuf:"varint,2,req,name=Type" json:"Type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Field) Reset()                    { *m = Field{} }
func (m *Field) String() string            { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()               {}
func (*Field) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{21} }

func (m *Field) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Field) GetType() uint64 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type FieldDimensionsResponse struct {
	Fields           []string `protobuf:"bytes,1,rep,name=Fields" json:"Fields,omitempty"`
	Dimensions       []string `protobuf:"bytes,2,rep,name=Dimensions" json:"Dimensions,omitempty"`
	Err              *string  `protobuf:"bytes,3,opt,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FieldDimensionsResponse) Reset()                    { *m = FieldDimensionsResponse{} }
func (m *FieldDimensionsResponse) String() string            { return proto.CompactTextString(m) }
func (*FieldDimensionsResponse) ProtoMessage()               {}
func (*FieldDimensionsResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{22} }

func (m *FieldDimensionsResponse) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *FieldDimensionsResponse) GetDimensions() []string {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func (m *FieldDimensionsResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type ExpandSourcesRequest struct {
	ShardIDs         []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Sources          []byte   `protobuf:"bytes,2,req,name=Sources" json:"Sources,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ExpandSourcesRequest) Reset()                    { *m = ExpandSourcesRequest{} }
func (m *ExpandSourcesRequest) String() string            { return proto.CompactTextString(m) }
func (*ExpandSourcesRequest) ProtoMessage()               {}
func (*ExpandSourcesRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{23} }

func (m *ExpandSourcesRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *ExpandSourcesRequest) GetSources() []byte {
	if m != nil {
		return m.Sources
	}
	return nil
}

type ExpandSourcesResponse struct {
	Sources          []byte  `protobuf:"bytes,1,opt,name=Sources" json:"Sources,omitempty"`
	Err              *string `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExpandSourcesResponse) Reset()                    { *m = ExpandSourcesResponse{} }
func (m *ExpandSourcesResponse) String() string            { return proto.CompactTextString(m) }
func (*ExpandSourcesResponse) ProtoMessage()               {}
func (*ExpandSourcesResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{24} }

func (m *ExpandSourcesResponse) GetSources() []byte {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *ExpandSourcesResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type DownloadShardSnapshotRequest struct {
	ShardID          *uint64 `protobuf:"varint,1,req,name=ShardID" json:"ShardID,omitempty"`
	Path             *string `protobuf:"bytes,2,req,name=Path" json:"Path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DownloadShardSnapshotRequest) Reset()         { *m = DownloadShardSnapshotRequest{} }
func (m *DownloadShardSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadShardSnapshotRequest) ProtoMessage()    {}
func (*DownloadShardSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorData, []int{25}
}

func (m *DownloadShardSnapshotRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *DownloadShardSnapshotRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type DownloadShardSnapshotResponse struct {
	Err              *string `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DownloadShardSnapshotResponse) Reset()         { *m = DownloadShardSnapshotResponse{} }
func (m *DownloadShardSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadShardSnapshotResponse) ProtoMessage()    {}
func (*DownloadShardSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorData, []int{26}
}

func (m *DownloadShardSnapshotResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type ShardStatusRequest struct {
	ShardID          *uint64 `protobuf:"varint,1,req,name=ShardID" json:"ShardID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ShardStatusRequest) Reset()                    { *m = ShardStatusRequest{} }
func (m *ShardStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*ShardStatusRequest) ProtoMessage()               {}
func (*ShardStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{27} }

func (m *ShardStatusRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

type ShardStatusResponse struct {
	Err              *string `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	Size_            *uint64 `protobuf:"varint,2,req,name=Size" json:"Size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ShardStatusResponse) Reset()                    { *m = ShardStatusResponse{} }
func (m *ShardStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*ShardStatusResponse) ProtoMessage()               {}
func (*ShardStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{28} }

func (m *ShardStatusResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *ShardStatusResponse) GetSize_() uint64 {
	if m != nil && m.Size_ != nil {
		return *m.Size_
	}
	return 0
}

type CreateShardSnapshotRequest struct {
	ShardID          *uint64 `protobuf:"varint,1,req,name=ShardID" json:"ShardID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateShardSnapshotRequest) Reset()                    { *m = CreateShardSnapshotRequest{} }
func (m *CreateShardSnapshotRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateShardSnapshotRequest) ProtoMessage()               {}
func (*CreateShardSnapshotRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{29} }

func (m *CreateShardSnapshotRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

type CreateShardSnapshotResponse struct {
	Err              *string `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	Path             *string `protobuf:"bytes,2,req,name=Path" json:"Path,omitempty"`
	Size_            *uint64 `protobuf:"varint,3,req,name=Size" json:"Size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateShardSnapshotResponse) Reset()                    { *m = CreateShardSnapshotResponse{} }
func (m *CreateShardSnapshotResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateShardSnapshotResponse) ProtoMessage()               {}
func (*CreateShardSnapshotResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{30} }

func (m *CreateShardSnapshotResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *CreateShardSnapshotResponse) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *CreateShardSnapshotResponse) GetSize_() uint64 {
	if m != nil && m.Size_ != nil {
		return *m.Size_
	}
	return 0
}

type DeleteShardSnapshotRequest struct {
	ShardID          *uint64 `protobuf:"varint,1,req,name=ShardID" json:"ShardID,omitempty"`
	Path             *string `protobuf:"bytes,2,req,name=Path" json:"Path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteShardSnapshotRequest) Reset()                    { *m = DeleteShardSnapshotRequest{} }
func (m *DeleteShardSnapshotRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteShardSnapshotRequest) ProtoMessage()               {}
func (*DeleteShardSnapshotRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{31} }

func (m *DeleteShardSnapshotRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *DeleteShardSnapshotRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type DeleteShardSnapshotResponse struct {
	Err              *string `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteShardSnapshotResponse) Reset()                    { *m = DeleteShardSnapshotResponse{} }
func (m *DeleteShardSnapshotResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteShardSnapshotResponse) ProtoMessage()               {}
func (*DeleteShardSnapshotResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{32} }

func (m *DeleteShardSnapshotResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type QueryInfo struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Query            *string `protobuf:"bytes,2,req,name=Query" json:"Query,omitempty"`
	User             *string `protobuf:"bytes,3,req,name=User" json:"User,omitempty"`
	Database         *string `protobuf:"bytes,4,req,name=Database" json:"Database,omitempty"`
	Duration         *int64  `protobuf:"varint,5,req,name=Duration" json:"Duration,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *QueryInfo) Reset()                    { *m = QueryInfo{} }
func (m *QueryInfo) String() string            { return proto.CompactTextString(m) }
func (*QueryInfo) ProtoMessage()               {}
func (*QueryInfo) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{33} }

func (m *QueryInfo) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *QueryInfo) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

func (m *QueryInfo) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *QueryInfo) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *QueryInfo) GetDuration() int64 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

type ShowQueriesRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ShowQueriesRequest) Reset()                    { *m = ShowQueriesRequest{} }
func (m *ShowQueriesRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowQueriesRequest) ProtoMessage()               {}
func (*ShowQueriesRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{34} }

type ShowQueriesResponse struct {
	Queries          *string `protobuf:"bytes,1,req,name=Queries" json:"Queries,omitempty"`
	Err              *string `protobuf:"bytes,2,req,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ShowQueriesResponse) Reset()                    { *m = ShowQueriesResponse{} }
func (m *ShowQueriesResponse) String() string            { return proto.CompactTextString(m) }
func (*ShowQueriesResponse) ProtoMessage()               {}
func (*ShowQueriesResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{35} }

func (m *ShowQueriesResponse) GetQueries() string {
	if m != nil && m.Queries != nil {
		return *m.Queries
	}
	return ""
}

func (m *ShowQueriesResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type KillQueryRequest struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KillQueryRequest) Reset()                    { *m = KillQueryRequest{} }
func (m *KillQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*KillQueryRequest) ProtoMessage()               {}
func (*KillQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{36} }

func (m *KillQueryRequest) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

type KillQueryResponse struct {
	Err              *string `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KillQueryResponse) Reset()                    { *m = KillQueryResponse{} }
func (m *KillQueryResponse) String() string            { return proto.CompactTextString(m) }
func (*KillQueryResponse) ProtoMessage()               {}
func (*KillQueryResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{37} }

func (m *KillQueryResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type RestoreShardRequest struct {
	ShardID          *uint64 `protobuf:"varint,1,req,name=ShardID" json:"ShardID,omitempty"`
	Size_            *uint64 `protobuf:"varint,2,req,name=Size" json:"Size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RestoreShardRequest) Reset()                    { *m = RestoreShardRequest{} }
func (m *RestoreShardRequest) String() string            { return proto.CompactTextString(m) }
func (*RestoreShardRequest) ProtoMessage()               {}
func (*RestoreShardRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{38} }

func (m *RestoreShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *RestoreShardRequest) GetSize_() uint64 {
	if m != nil && m.Size_ != nil {
		return *m.Size_
	}
	return 0
}

type RestoreShardResponse struct {
	Err              *string `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RestoreShardResponse) Reset()                    { *m = RestoreShardResponse{} }
func (m *RestoreShardResponse) String() string            { return proto.CompactTextString(m) }
func (*RestoreShardResponse) ProtoMessage()               {}
func (*RestoreShardResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{39} }

func (m *RestoreShardResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type ShowMeasurementsRequest struct {
	Err *string `protobuf:"bytes,1,req,name=Err" json:"Err,omitempty"`
	// Not sure what should be used for Condition, use string for now
	Condition        *string `protobuf:"bytes,2,req,name=Condition" json:"Condition,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ShowMeasurementsRequest) Reset()                    { *m = ShowMeasurementsRequest{} }
func (m *ShowMeasurementsRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowMeasurementsRequest) ProtoMessage()               {}
func (*ShowMeasurementsRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{40} }

func (m *ShowMeasurementsRequest) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *ShowMeasurementsRequest) GetCondition() string {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return ""
}

type ShowMeasurementsResponse struct {
	Measurements     *string `protobuf:"bytes,1,req,name=Measurements" json:"Measurements,omitempty"`
	Err              *string `protobuf:"bytes,2,req,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ShowMeasurementsResponse) Reset()                    { *m = ShowMeasurementsResponse{} }
func (m *ShowMeasurementsResponse) String() string            { return proto.CompactTextString(m) }
func (*ShowMeasurementsResponse) ProtoMessage()               {}
func (*ShowMeasurementsResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{41} }

func (m *ShowMeasurementsResponse) GetMeasurements() string {
	if m != nil && m.Measurements != nil {
		return *m.Measurements
	}
	return ""
}

func (m *ShowMeasurementsResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type KeyValue struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{42} }

func (m *KeyValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type TagValues struct {
	Measurement      *string `protobuf:"bytes,1,req,name=Measurement" json:"Measurement,omitempty"`
	Values           *string `protobuf:"bytes,2,req,name=Values" json:"Values,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TagValues) Reset()                    { *m = TagValues{} }
func (m *TagValues) String() string            { return proto.CompactTextString(m) }
func (*TagValues) ProtoMessage()               {}
func (*TagValues) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{43} }

func (m *TagValues) GetMeasurement() string {
	if m != nil && m.Measurement != nil {
		return *m.Measurement
	}
	return ""
}

func (m *TagValues) GetValues() string {
	if m != nil && m.Values != nil {
		return *m.Values
	}
	return ""
}

type ShowTagValuesRequest struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Condition        *string `protobuf:"bytes,2,req,name=Condition" json:"Condition,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ShowTagValuesRequest) Reset()                    { *m = ShowTagValuesRequest{} }
func (m *ShowTagValuesRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowTagValuesRequest) ProtoMessage()               {}
func (*ShowTagValuesRequest) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{44} }

func (m *ShowTagValuesRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *ShowTagValuesRequest) GetCondition() string {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return ""
}

type ShowTagValuesResponse struct {
	Values           []byte  `protobuf:"bytes,1,req,name=Values" json:"Values,omitempty"`
	Err              *string `protobuf:"bytes,2,req,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ShowTagValuesResponse) Reset()                    { *m = ShowTagValuesResponse{} }
func (m *ShowTagValuesResponse) String() string            { return proto.CompactTextString(m) }
func (*ShowTagValuesResponse) ProtoMessage()               {}
func (*ShowTagValuesResponse) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{45} }

func (m *ShowTagValuesResponse) GetValues() []byte {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ShowTagValuesResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*CopyShardRequest)(nil), "internal.CopyShardRequest")
	proto.RegisterType((*CopyShardResponse)(nil), "internal.CopyShardResponse")
	proto.RegisterType((*CopyShardStatusRequest)(nil), "internal.CopyShardStatusRequest")
	proto.RegisterType((*CopyShardStatusResponse)(nil), "internal.CopyShardStatusResponse")
	proto.RegisterType((*CopyShardStatus)(nil), "internal.CopyShardStatus")
	proto.RegisterType((*KillCopyShardRequest)(nil), "internal.KillCopyShardRequest")
	proto.RegisterType((*KillCopyShardResponse)(nil), "internal.KillCopyShardResponse")
	proto.RegisterType((*RemoveShardRequest)(nil), "internal.RemoveShardRequest")
	proto.RegisterType((*RemoveShardResponse)(nil), "internal.RemoveShardResponse")
	proto.RegisterType((*JoinClusterRequest)(nil), "internal.JoinClusterRequest")
	proto.RegisterType((*JoinClusterResponse)(nil), "internal.JoinClusterResponse")
	proto.RegisterType((*LeaveClusterRequest)(nil), "internal.LeaveClusterRequest")
	proto.RegisterType((*LeaveClusterResponse)(nil), "internal.LeaveClusterResponse")
	proto.RegisterType((*WriteShardRequest)(nil), "internal.WriteShardRequest")
	proto.RegisterType((*WriteShardResponse)(nil), "internal.WriteShardResponse")
	proto.RegisterType((*ExecuteStatementRequest)(nil), "internal.ExecuteStatementRequest")
	proto.RegisterType((*ExecuteStatementResponse)(nil), "internal.ExecuteStatementResponse")
	proto.RegisterType((*CreateIteratorRequest)(nil), "internal.CreateIteratorRequest")
	proto.RegisterType((*CreateIteratorResponse)(nil), "internal.CreateIteratorResponse")
	proto.RegisterType((*IteratorStats)(nil), "internal.IteratorStats")
	proto.RegisterType((*FieldDimensionsRequest)(nil), "internal.FieldDimensionsRequest")
	proto.RegisterType((*Field)(nil), "internal.Field")
	proto.RegisterType((*FieldDimensionsResponse)(nil), "internal.FieldDimensionsResponse")
	proto.RegisterType((*ExpandSourcesRequest)(nil), "internal.ExpandSourcesRequest")
	proto.RegisterType((*ExpandSourcesResponse)(nil), "internal.ExpandSourcesResponse")
	proto.RegisterType((*DownloadShardSnapshotRequest)(nil), "internal.DownloadShardSnapshotRequest")
	proto.RegisterType((*DownloadShardSnapshotResponse)(nil), "internal.DownloadShardSnapshotResponse")
	proto.RegisterType((*ShardStatusRequest)(nil), "internal.ShardStatusRequest")
	proto.RegisterType((*ShardStatusResponse)(nil), "internal.ShardStatusResponse")
	proto.RegisterType((*CreateShardSnapshotRequest)(nil), "internal.CreateShardSnapshotRequest")
	proto.RegisterType((*CreateShardSnapshotResponse)(nil), "internal.CreateShardSnapshotResponse")
	proto.RegisterType((*DeleteShardSnapshotRequest)(nil), "internal.DeleteShardSnapshotRequest")
	proto.RegisterType((*DeleteShardSnapshotResponse)(nil), "internal.DeleteShardSnapshotResponse")
	proto.RegisterType((*QueryInfo)(nil), "internal.QueryInfo")
	proto.RegisterType((*ShowQueriesRequest)(nil), "internal.ShowQueriesRequest")
	proto.RegisterType((*ShowQueriesResponse)(nil), "internal.ShowQueriesResponse")
	proto.RegisterType((*KillQueryRequest)(nil), "internal.KillQueryRequest")
	proto.RegisterType((*KillQueryResponse)(nil), "internal.KillQueryResponse")
	proto.RegisterType((*RestoreShardRequest)(nil), "internal.RestoreShardRequest")
	proto.RegisterType((*RestoreShardResponse)(nil), "internal.RestoreShardResponse")
	proto.RegisterType((*ShowMeasurementsRequest)(nil), "internal.ShowMeasurementsRequest")
	proto.RegisterType((*ShowMeasurementsResponse)(nil), "internal.ShowMeasurementsResponse")
	proto.RegisterType((*KeyValue)(nil), "internal.KeyValue")
	proto.RegisterType((*TagValues)(nil), "internal.TagValues")
	proto.RegisterType((*ShowTagValuesRequest)(nil), "internal.ShowTagValuesRequest")
	proto.RegisterType((*ShowTagValuesResponse)(nil), "internal.ShowTagValuesResponse")
}

func init() { proto.RegisterFile("internal/data.proto", fileDescriptorData) }

var fileDescriptorData = []byte{
	// 926 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x56, 0x6d, 0x6f, 0xdb, 0x36,
	0x10, 0x86, 0x6d, 0xb9, 0x89, 0xae, 0x4a, 0x13, 0xcb, 0x4e, 0x2c, 0xb4, 0xdb, 0x60, 0x28, 0xeb,
	0x66, 0x0c, 0x7b, 0x09, 0xd0, 0x76, 0x40, 0x11, 0x74, 0x40, 0x61, 0xa7, 0x9b, 0x9b, 0x25, 0xcb,
	0x62, 0xef, 0xe5, 0xdb, 0xc0, 0x59, 0xb7, 0x46, 0x98, 0x2c, 0x7a, 0x24, 0xd5, 0xd6, 0xfb, 0x0d,
	0xfb, 0xd1, 0x03, 0x5f, 0x2c, 0x51, 0xb2, 0x8c, 0x26, 0x1f, 0x75, 0xbc, 0xbb, 0xe7, 0xb9, 0xe7,
	0x8e, 0x47, 0x41, 0x37, 0x4e, 0x05, 0xb2, 0x94, 0x24, 0xdf, 0x44, 0x44, 0x90, 0xaf, 0x97, 0x8c,
	0x0a, 0xea, 0xef, 0xae, 0x8d, 0xe1, 0x1c, 0x0e, 0x46, 0x74, 0xb9, 0x9a, 0xde, 0x10, 0x16, 0x5d,
	0xe3, 0x3f, 0x19, 0x72, 0xe1, 0x3f, 0x80, 0x7b, 0x53, 0x9a, 0xb1, 0x39, 0x06, 0x8d, 0x41, 0x73,
	0xe8, 0xfa, 0x1e, 0x38, 0x63, 0xe4, 0x22, 0x68, 0xaa, 0xaf, 0x03, 0xd8, 0x1d, 0x13, 0x41, 0xfe,
	0x24, 0x1c, 0x83, 0xd6, 0xa0, 0x31, 0x74, 0xa5, 0xff, 0x15, 0x4d, 0xe2, 0xf9, 0x2a, 0x70, 0x94,
	0xc7, 0x3e, 0xec, 0xa8, 0x7c, 0x93, 0x71, 0xd0, 0x1e, 0x34, 0x87, 0x4e, 0x38, 0x80, 0x8e, 0x05,
	0xc2, 0x97, 0x34, 0xe5, 0xe8, 0xdf, 0x87, 0xd6, 0x19, 0x63, 0x1a, 0x22, 0x0c, 0xe0, 0x28, 0xf7,
	0x98, 0x0a, 0x22, 0x32, 0x6e, 0xc8, 0x84, 0xcf, 0xa0, 0xbf, 0x71, 0x52, 0x93, 0xc1, 0xdf, 0x83,
	0xf6, 0x8c, 0xf0, 0xbf, 0xb9, 0x66, 0x19, 0xfe, 0xd7, 0x80, 0xfd, 0x4a, 0xdc, 0x9d, 0xea, 0x6a,
	0xd6, 0xd4, 0xd5, 0x01, 0x77, 0x46, 0x05, 0x49, 0xa6, 0xf1, 0xbf, 0xa8, 0x2b, 0xf3, 0xbb, 0x70,
	0x7f, 0x9e, 0x31, 0x86, 0xa9, 0x50, 0xc6, 0x7b, 0xca, 0xd8, 0x01, 0x77, 0x2a, 0x08, 0x13, 0x18,
	0xbd, 0x14, 0xc1, 0x8e, 0x52, 0xe0, 0x0c, 0x7a, 0xe7, 0x71, 0x92, 0xdc, 0x51, 0x6a, 0x4b, 0xc8,
	0x96, 0x4a, 0xf3, 0x29, 0x1c, 0x56, 0xd2, 0xd4, 0x89, 0xf9, 0x3d, 0xf8, 0xd7, 0xb8, 0xa0, 0x6f,
	0xb1, 0x04, 0x65, 0xd7, 0xd7, 0xa8, 0xd4, 0xb7, 0x05, 0x2e, 0x84, 0x6e, 0x29, 0x51, 0x1d, 0x18,
	0x01, 0xff, 0x35, 0x8d, 0xd3, 0x51, 0x92, 0x71, 0x81, 0xcc, 0xaa, 0xeb, 0x92, 0x46, 0x38, 0x89,
	0x94, 0x97, 0x23, 0xc1, 0xe5, 0xf7, 0xcb, 0x28, 0x62, 0x06, 0xac, 0x03, 0xee, 0x05, 0x0a, 0x22,
	0x2d, 0xdc, 0xe8, 0x7d, 0x04, 0x0f, 0x26, 0x8b, 0x25, 0x65, 0x42, 0x1e, 0x48, 0xae, 0x5a, 0xf7,
	0x70, 0x04, 0xdd, 0x12, 0x84, 0xa1, 0xb1, 0xc6, 0x18, 0x1b, 0x8c, 0x7d, 0xd8, 0x99, 0x8d, 0xae,
	0x7e, 0xa0, 0xb9, 0x7c, 0x86, 0xa7, 0x4a, 0x1e, 0x7e, 0x0e, 0xdd, 0x1f, 0x91, 0xbc, 0xc5, 0x0a,
	0x51, 0x9b, 0x98, 0x2e, 0xe8, 0x18, 0x7a, 0x65, 0xc7, 0xba, 0xaa, 0xff, 0x80, 0xce, 0x6f, 0x2c,
	0x16, 0x65, 0x85, 0x2d, 0xfd, 0x34, 0x23, 0x25, 0x70, 0x9c, 0x0a, 0x39, 0x94, 0xad, 0xa1, 0x57,
	0x73, 0x75, 0xfa, 0xb0, 0x7f, 0x8d, 0x02, 0x53, 0x11, 0xd3, 0x34, 0x9f, 0xb5, 0xc6, 0xd0, 0x0d,
	0x9f, 0x80, 0x6f, 0x03, 0x18, 0x0e, 0x1e, 0x38, 0x23, 0x1a, 0xe9, 0xfe, 0xb5, 0x25, 0xde, 0x05,
	0x72, 0x4e, 0xde, 0x60, 0xd0, 0x54, 0x41, 0xdf, 0x41, 0xff, 0xec, 0x3d, 0xce, 0x33, 0x81, 0x72,
	0xe2, 0x71, 0x81, 0xa9, 0x58, 0x73, 0xd3, 0x33, 0xa9, 0x6d, 0xa6, 0xfd, 0x36, 0x1b, 0x7d, 0x69,
	0x9e, 0x43, 0xb0, 0x19, 0x7f, 0x3b, 0xe8, 0x6f, 0xe1, 0x70, 0xc4, 0x90, 0x08, 0x9c, 0x08, 0x64,
	0x44, 0x50, 0x5b, 0x60, 0x23, 0x0a, 0x0f, 0x1a, 0x83, 0xd6, 0xd0, 0x91, 0x42, 0xfe, 0xb4, 0xd4,
	0x3d, 0xf2, 0xc2, 0xc7, 0x70, 0x54, 0x8d, 0xab, 0xea, 0x2d, 0xd3, 0x9f, 0xc0, 0xde, 0xda, 0x41,
	0x52, 0xe3, 0x4a, 0x6b, 0x64, 0x31, 0xf2, 0xcb, 0x8a, 0xd6, 0x97, 0x26, 0xf1, 0x29, 0x1c, 0xbd,
	0x8a, 0x31, 0x89, 0xc6, 0xf1, 0x02, 0x53, 0x1e, 0xd3, 0x94, 0x6f, 0x67, 0x24, 0x93, 0xa9, 0x5b,
	0xc8, 0x4d, 0xf0, 0x31, 0xb4, 0x55, 0xb0, 0xac, 0xfa, 0x92, 0x2c, 0xac, 0xdb, 0x39, 0x5b, 0x2d,
	0xb5, 0x5a, 0x4e, 0xf8, 0x1a, 0xfa, 0x1b, 0x08, 0xc5, 0x68, 0xaa, 0x23, 0x0d, 0xe0, 0xfa, 0x3e,
	0x40, 0xe1, 0xa5, 0x86, 0xc1, 0x9a, 0xce, 0x86, 0x52, 0xbe, 0x77, 0xf6, 0x7e, 0x49, 0xd2, 0xc8,
	0xf0, 0xb8, 0x03, 0xd7, 0x67, 0x70, 0x58, 0x09, 0x35, 0x24, 0x2c, 0x4f, 0x29, 0xa2, 0xb7, 0x46,
	0xd4, 0x0d, 0x7b, 0x01, 0x1f, 0x8d, 0xe9, 0xbb, 0x34, 0xa1, 0x24, 0xd2, 0x3b, 0x32, 0x25, 0x4b,
	0x7e, 0x43, 0xc5, 0xd6, 0x61, 0xf6, 0xc0, 0xb9, 0x22, 0xe2, 0xc6, 0x8c, 0xca, 0x97, 0xf0, 0xf1,
	0x96, 0xf0, 0xba, 0xf6, 0x3d, 0x06, 0x7f, 0x73, 0xb5, 0x6f, 0x40, 0x84, 0x27, 0xd0, 0xfd, 0xe0,
	0x9e, 0xf7, 0xc0, 0x51, 0xab, 0x56, 0xf7, 0xe0, 0x2b, 0x78, 0xa8, 0xc7, 0xe7, 0x56, 0x35, 0x84,
	0xaf, 0xe0, 0x51, 0xad, 0xfb, 0x16, 0xa0, 0xa2, 0xde, 0x1c, 0x56, 0x2f, 0xc6, 0x53, 0x78, 0x38,
	0xc6, 0x04, 0x6f, 0x09, 0x5b, 0x91, 0xee, 0x0b, 0x78, 0x54, 0x1b, 0x5c, 0xb7, 0x67, 0x7e, 0x07,
	0xf7, 0xe7, 0x0c, 0xd9, 0x6a, 0x92, 0xfe, 0x45, 0x7d, 0x80, 0x66, 0x9e, 0x72, 0x0f, 0xda, 0xea,
	0xa0, 0xa0, 0xf7, 0x0b, 0x47, 0xb3, 0xeb, 0x4a, 0x37, 0xdb, 0xc9, 0x2d, 0x19, 0x23, 0x72, 0xcd,
	0xa8, 0x97, 0xab, 0x15, 0xf6, 0x64, 0x4b, 0xe8, 0x3b, 0x99, 0x24, 0xce, 0xe7, 0x2d, 0x7c, 0x22,
	0x3b, 0x60, 0x59, 0x8b, 0x51, 0x32, 0x26, 0x23, 0x4e, 0x3e, 0x4a, 0x92, 0xe4, 0x27, 0x70, 0x20,
	0x5f, 0x25, 0xc5, 0x67, 0xad, 0x81, 0xc5, 0x55, 0x3e, 0xff, 0xd6, 0x79, 0x5d, 0x99, 0x4f, 0xe5,
	0x43, 0xc3, 0x05, 0x65, 0x1f, 0x58, 0xa8, 0xe5, 0xe6, 0x1f, 0x43, 0xaf, 0x1c, 0x55, 0x97, 0xfa,
	0x39, 0xf4, 0x65, 0x45, 0x17, 0x48, 0x78, 0xc6, 0xd4, 0x4a, 0xcb, 0xe7, 0xaf, 0xd4, 0xee, 0x0e,
	0xb8, 0x23, 0x9a, 0x46, 0xb1, 0x92, 0x48, 0xd7, 0xf5, 0x02, 0x82, 0xcd, 0x50, 0x83, 0xd1, 0x03,
	0xcf, 0xb6, 0xd7, 0xc9, 0xf2, 0x19, 0xec, 0x9e, 0xe3, 0xea, 0x57, 0x92, 0x64, 0x8a, 0xd2, 0x39,
	0xae, 0x8a, 0x5f, 0x15, 0x65, 0x35, 0x7e, 0x27, 0xe0, 0xce, 0xc8, 0x1b, 0x65, 0xe1, 0xf2, 0x87,
	0xc2, 0xca, 0x5b, 0x3c, 0xd4, 0xfa, 0xd8, 0x44, 0x9c, 0x42, 0x4f, 0x12, 0xcb, 0xa3, 0xb6, 0x3f,
	0xf1, 0x35, 0x55, 0x3d, 0x85, 0xc3, 0x4a, 0x70, 0xb1, 0xb4, 0x0c, 0x8a, 0x8c, 0xf5, 0x4a, 0xc5,
	0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xdb, 0x98, 0xe4, 0x47, 0x0a, 0x00, 0x00,
}
